### ISSUE TITLE
Reproducibility and assertion via CI

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#10]
One of the important goals of rules_container is to be reproducible. the final image should be canonical as long as the compilation target is the same. we should assert this with our CI pipeline.

A few examples of this would be

- host `darwin/arm64`  cross-compiling to `linux/arm64`
- host `darwin/amd64`  cross-compiling to `linux/arm64`
- host `linux/armel` cross-compiling to `linux/arm64`
- host `linux/arm64` compiling to `linux/arm64`
- host `windows/amd64`  cross-compiling to `linux/arm64`

with all of the cases above, the resulting image should be canonical and have the same digest. this is a realistic goal as long as the upstream `*_binary` rules are deterministic and spit the same `runfiles` regardless of the host platform.

there are a few things to be careful about in order to ensure reproducibility.
- stamping
- `history` property in image config
- `--mtime` embedded in tar layers.
- `--sort=name` file ordering in tar layers.
- `--owner=0 --group=0 --numeric-owner` in tar layers.
- strip PAX headers from tar layers.

**Comment by thesayyn** [comment]
> * strip PAX headers from tar layers.

this might not work if we ever support building Windows containers.

**Comment by thesayyn** [comment]
> It looks like container base images are not treated hermetically at present? If I'm reading it right they're going to get downloaded during the execution phase by `crane mutate <base>`, so will not be subject to remote caching, Bazel integrity checks, invalidation, etc. Those seems like important aspects for reproducibility.

You are right. container_pull functionality is basically missing at the moment and #33 will remove the `crane mutate` behavior.  I have been thinking about supporting  container_pull which is capable of shallow pulling, remote cacheable via `rctx.download`,  and integrity-checked blobs but don't have the time and resources to implement that yet.

**Comment by thesayyn** [comment]
> We implemented a hermetic `oci_pull` rule now. Is there more to do for this issue?

only thing left from this list is asserting oci_image produces the same output with a clean build.

**Comment by alexeagle** [comment]
I guess we can just make a golden file test against the digest we produce in our e2e test
