### ISSUE TITLE
bzlmod - how to use oci_pull?

### ISSUE THREAD

**Issue by acr92** [bazel-contrib/rules_oci#100]
I don't see any examples for how to use oci_pull with bzlmod. Is this not supported?

Typically it's an extension function (e.g. with rules_jvm_external there's a "maven" function with a `maven.install` method), but I couldn't see that being supported in rules_oci.

**Comment by seh** [comment]
This [came up yesterday in the "bzlmod" channel](https://bazelbuild.slack.com/archives/C014RARENH0/p1678969401406399) of the "Bazel" Slack workspace. There, I discovered that if I want to use the `oci_pull` rule, I need to define the corresponding targets in my _WORKSPACE.bzlmod_ file, which means that I then also need to declare Bazel module dependencies in my _MODULE.bazel_ file for any repositories loaded by _rules_oci_'s `oci_pull` (e.g. _aspect_bazel_lib_).

That got me thinking that we'd benefit from a module extension function that would allow pulling OCI images from the _MODULE.bazel_ file, which would then remove the need to use a _WORKSPACE.bzlmod_ file. Are there any plans for such a module extension?

@alexeagle, I expect that you'll know best.

**Comment by alexeagle** [comment]
Fixed in #118

**Comment by alexeagle** [comment]
Example: https://github.com/aspect-build/bazel-examples/blob/main/oci_go_image/MODULE.bazel#L20-L28
