### ISSUE TITLE
Question: is it possible to run a container as an executable in an sh_binary or sh_test?

### ISSUE THREAD

**Issue by njlr** [bazel-contrib/rules_oci#103]
I was wondering if it possible to run a `container_image` (using the Bazel configured toolchain) inside of an `sh_binary` or `sh_test`? This would be a powerful feature, for example to test code that only works inside of a particular container. 

If it is possible, is there an example of this?

**Comment by thesayyn** [comment]
Do you mean loading the `oci_image` target into the daemon and asserting its behavior with a bash test?

**Comment by thesayyn** [comment]
We have `structure_test` for that. https://github.com/bazel-contrib/rules_oci/blob/a66598d8f2754e09e124f73136c4b33634044b7d/examples/env_inheritance/BUILD.bazel#L25-L29 which uses https://github.com/GoogleContainerTools/container-structure-test under the hood

**Comment by njlr** [comment]
Ah thank you. It sounds like I am looking for `commandTests`.
