### ISSUE TITLE
Docker authentication using `desktop` as credsStore not working

### ISSUE THREAD

**Issue by troels-im** [bazel-contrib/rules_oci#124]
## What happens?

After upgrading to version 0.3.8, I am experiencing following issue when attempting to pull a image from docker hub:

```
`Error: key "auths" not found in dictionary
```

## Why does it happen?

After a fresh install of Docker on macOS and login in via the terminal, the `config.json` looks like:
```sh
% docker login
Authenticating with existing credentials...
Login Succeeded

Logging in with your password grants your terminal complete access to your account.
For better security, log in with a limited-privilege personal access token. Learn more at https://docs.docker.com/go/access-tokens/
% cat  ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "desktop"
}%
```

## Workaround

For those who wants to work around this, you can update `config.json` with `"credsStore": ""` and then login again. This will populate the `auth` field in the dictionary for `https://index.docker.io/v1/`.

**Comment by thesayyn** [comment]
fixed by #131
