### ISSUE TITLE
FR: oci_pull support identity tokens

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#129]
credHelper response with `{"Username": "<token>"}` should be handled differently. 

See https://github.com/moby/moby/issues/36926

**Comment by wingsofovnia** [comment]
Any updates? Is there any priority assigned to this issue or perhaps there are blockers?

**Comment by thesayyn** [comment]
No, PRs are welcome.

**Comment by BradHolmes** [comment]
This small change in `authn.bzl` got things working for me.  Anything else needed?  

```
     if response["Username"] == "<token>":
-        fail("Identity tokens are not supported at the moment. See: https://github.com/bazel-contrib/rules_oci/issues/129")
+        return {
+            "type": "pattern",
+            "pattern": "Bearer <password>",
+            "password": response["Secret"],
+        }
```

I don't really have a good idea about adding an example or test though.

**Comment by wingsofovnia** [comment]
Should be fixed by https://github.com/bazel-contrib/rules_oci/pull/626

**Comment by thesayyn** [comment]
Closing as fixed.
