### ISSUE TITLE
[discussion] allow oci_pull with tag + digest

### ISSUE THREAD

**Issue by malt3** [bazel-contrib/rules_oci#139]
This is a follow-up from https://github.com/renovatebot/renovate/pull/21216

Dependency management tools like renovate can use the tag of a container image for more informed upgrades
Users can even define custom policies and versioning schemes to have fine control over what upgrades should be suggested.

> I could see us allowing both tag and digest to be set and making digest override tag.
@thesayyn

**Comment by Cartman75** [comment]
I would like this. As stated. When renovate send me an update, I understand the difference between just hash updates because the container changed with the same version and when the actual version of the image is changing, not just the hash.

**Comment by thesayyn** [comment]
Discussion is ongoing at https://github.com/bazel-contrib/rules_oci/issues/391
