### ISSUE TITLE
No such package '@debian_linux_amd64

### ISSUE THREAD

**Issue by flolu** [bazel-contrib/rules_oci#149]
## Minimal Reproduction

```
git clone https://github.com/flolu/rules_oci-debian
cd rules_oci-debian
pnpm i
bazel build //app:image_tar
docker load --input $(bazel cquery --output=files //app:image_tar)
docker run -t rules_oci_debian_repro:latest
```

## Error on Linux

During `bazel build //app:image_tar`

```
ERROR: /home/flolu/.cache/bazel/_bazel_flolu/3af270419fb798df87446cdc0a5f5c5f/external/debian/BUILD.bazel:1:6: @debian//:debian depends on @debian_linux_amd64//:debian_linux_amd64 in repository @debian_linux_amd64 which failed to fetch. no such package '@debian_linux_amd64//': key "auths" not found in dictionary
```

## Error on macOS

During `docker run -t rules_oci_debian_repro:latest`

```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

## Notes

Everything works fine, when not using [`load("@rules_oci//oci:pull.bzl", "oci_pull")` in `WORKSPACE`](https://github.com/flolu/rules_oci-debian/blob/8c87090dbf893f7d9efc848cb1ec409722bddaca/WORKSPACE#L120) and rather using [pull.bzl](https://github.com/flolu/rules_oci-debian/blob/main/pull.bzl)

**Comment by seh** [comment]
This sounds similar to bazelbuild/bazel#17655. Does this work if you use a more recent Bazel version including bazelbuild/bazel#17818, such as _last_green_ via Basilisk?

**Comment by flolu** [comment]
Mh. I've tried with `last_green` version, but I get the same error

**Comment by flolu** [comment]
The issue seems to be fixed with the v1 release of rules_oci
