### ISSUE TITLE
Stamp labels/annotations

### ISSUE THREAD

**Issue by pauldraper** [bazel-contrib/rules_oci#152]
The image label/annotations should be stampable.

For example, Datadog (monitoring) can use this information to link to a VCS revision.

In rules_docker, labels are stampable.

**Comment by alexeagle** [comment]
@pauldraper nice to work with you again :)

**Comment by pauldraper** [comment]
Thanks :) same

**Comment by sfc-gh-ptabor** [comment]
Hi, 
Have you discussed ability to stamp 'env' as well, or at least allow to pass :label to the 'env' flag ?

1. Ability to pass file/:label would make the solution consistent, it is, `env`, `annotations` and `label` would have the same capability and ability to support generated content.  

2. Automated stamping - would make migration from `docker_rules` easier, as the `env` is stamped there. 
I assume we prefer users to generate a file within docker images with the 'stamp' values if the app depend on them, rather passing them as 'environment'.  

Happy to contribute a PR (for either 1. or 2.), but just checking whether you will find it aligned with the product direction.

**Comment by sfc-gh-ptabor** [comment]
- If I understand the code correctly, the labels and annotations are not `stamped` automatically. They just can be stamped by a separate rule generating the file. Correct ?

**Comment by pauldraper** [comment]
Correct. For example, you could use a stamp-enabled genrule to generate the labels/annotations, and then pass that to the OCI rule.

This removes any complexity of value interpolation from these rules.

**Comment by sfc-gh-ptabor** [comment]
Thanks @pauldraper  for the confirmation.
 
How about enabling 'env' to take a file - the same way you did for annotations and labels ?
