### ISSUE TITLE
zot isn't ready in time (5s), perhaps this should be configurable?

### ISSUE THREAD

**Issue by loosebazooka** [bazel-contrib/rules_oci#170]
On large builds, sometime I see errors like:
```
registry didn't become ready within 5s.
```

I don't know if zot needs more time to start up, but could this be configurable?

**Comment by thesayyn** [comment]
I have been seeing this happening on our GHA CI as well. I agree that this should be configurable.

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/550
