### ISSUE TITLE
Suggest installing rules_python rather than rules_pkg_dependencies

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#177]
our snippet says:
```
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()
```

But that thing gives a very old rules_python. We could
- stop depending on rules_pkg (?)
- fix rules_pkg to have "modern" python
- give install snippet that inlines rules_pkg_dependencies

**Comment by alexeagle** [comment]
Filed upstrem https://github.com/bazelbuild/rules_pkg/issues/698

**Comment by thesayyn** [comment]
drop rules_pkg and just depend on system tar program.
