### ISSUE TITLE
oci_tarball: provide easy "bazel runnable" target to load into the daemon

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#180]
So we don't have to put comments above each `oci_tarball` saying how to build/load/run the image.

It can print a "next, run `docker run bazel/the/image:bazel ` command for you to know what's next after loading it.

**Comment by ewhauser** [comment]
@alexeagle I have a patch available for this. What are you thinking in regards to extensibility for the container engine? I'm just using docker in the script but could expose a `run_template` argument allowing it to be overridden? Longer term, it might make sense to expose a toolchain for the local container engine?

**Comment by ewhauser** [comment]
I've submitted a PR with a strawman implementation and we can discuss there

**Comment by thesayyn** [comment]
> I've submitted a PR with a strawman implementation and we can discuss there

looks like the PR introduces changes that runs `docker run` which isn't what we want. we only want to load it into the daemon. running it should happen outside of bazel as it becomes confusing what `runtime_args` does in this case.

**Comment by ewhauser** [comment]
Understood why that would not be desired. Submitted a new PR: https://github.com/bazel-contrib/rules_oci/pull/290

**Comment by sfc-gh-ptabor** [comment]
I assume it can be closed now as 'implemented'. Thank you for this feature.
