### ISSUE TITLE
Files on top layer (tar) not found

### ISSUE THREAD

**Issue by iangudger** [bazel-contrib/rules_oci#181]
I'm using version `85b695c9b953c3a96d46c116e8fa7af3026588f1`.

I have an image that I am building with `oci_image`. It has a base of `gcr.io/distroless/cc` (`sha256:ceab2b378860e134f3b470f153fbd1117b81438ae51ab97e2568149e9883cd32`) and a single tar. The tar contains at the top level a directory named `app.runfiles` and a symlink named `app` which points inside the `app.runfiles` directory. The `oci_image` is configured with an entrypoint of `/app`. This configuration works with my Go programs, but doesn't work with a Python program. The Python program fails to start with `exec /app: no such file or directory`.

I've tried:

1. Replacing the entrypoint with the path the symlink points to. This also results in a `exec app.runfiles/path/to/file: no such file or directory` error.
2. Extracting the layer and running it locally (with and without the symlink). This works as expected.
3. Running the image locally with Docker and on Kubernetes. Same error.
4. Setting the entry point to something in the distroless cc image. This works as expected.
5. Exporting the image from Docker as a tar. The image has the expected layout with `app` at the top level. Running via the symlink works as expected.

I'm beginning to think that `oci_image` is constructing the image in such a way that it is confusing tooling.

**Comment by thesayyn** [comment]
> I'm beginning to think that `oci_image` is constructing the image in such a way that it is confusing tooling.

oci_image doesn't do anything particular about layers. they are passed to the underlying tool interim. 

> This configuration works with my Go programs, but doesn't work with a Python program. The Python program fails to start with `exec /app: no such file or directory`.

I believe the hint is here. generally, py executables end with `.py` which can't be run directly without using the py interpreter. OTOH go programs are standalone executables with dynamically linked system libraries. 

I'd be happy to answer your questions, provided with an example demonstrating the issue.

**Comment by iangudger** [comment]
The issue is that while `rules_python` does use a hermetic Python interpreter, it requires an existing Python interpreter to bootstrap. Further, the bootstrap Python script uses `/usr/bin/env` to find the Python interpreter, and `/usr/bin/env` is not included in distroless images.

In other words, when Docker prints `exec /app: no such file or directory`, it actually means `exec /usr/bin/env: no such file or directory`.

https://github.com/bazelbuild/rules_docker/blob/6db7c12fbe4b49682f5dcbc193e4c467011a9fb6/python3/image.bzl#L116
