### ISSUE TITLE
flaky/slow mac CI due to podman

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#186]
Ideally we'd run on a Mac GHA hosted runner that has a docker or podman already installed.

I did some research and it seems like no one has requested podman be on the default `macos-latest` github runner that GH provides. They rejected docker due to licensing.

We could just restrict our testing to `driver = "tar"` so we don't actually need a docker/podman runtime on the CI machine. Would still get some useful MacOS coverage, likely.

@thesayyn I tried booting up an old Mac Mini from 2011 but it seems too old to build the stuff.

```
$ brew upgrade curl
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

**Comment by thesayyn** [comment]
@alexeagle can we close this in favor of https://github.com/bazel-contrib/rules_oci/issues/198?

**Comment by thesayyn** [comment]
closing this in favor of https://github.com/bazel-contrib/rules_oci/issues/198
