### ISSUE TITLE
Setup macos CI

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#198]
We removed it in https://github.com/bazel-contrib/rules_oci/pull/194 because setting up `podman` on GH Actions runners was too flaky (and the flake was often a hang with a 2h timeout)

**Comment by alexeagle** [comment]
@bsideup this is where we'd love to demonstrate that Bazel + TestContainers Cloud is a nice combo, and can show off an open-source project that doesn't need to figure out a container runtime on the CI runners

**Comment by thesayyn** [comment]
Closing this now as we have coverage on macos.
