### ISSUE TITLE
oci_push documentation does not provide any information on how to pass credentials

### ISSUE THREAD

**Issue by AttilaTheFun** [bazel-contrib/rules_oci#229]
I'm using AWS ECR for some lambda images and I want to push them to ECR with oci_push
Unfortunately the documentation does not mention at all how to provide credentials.
Do we have to manage these through crane?

In the docker world I store credentials in docker with:
```
aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
```

And then I push with docker:
```
docker push aws_account_id.dkr.ecr.us-west-2.amazonaws.com/my-repository:tag
```

How would I accomplish this with rules_oci?

**Comment by thesayyn** [comment]
running the oci_push target is basically equivalent to running docker push. whatever works outside of oci_push should work with oci_push basically.

**Comment by AttilaTheFun** [comment]
Thanks @thesayyn! To be clear, when running oci_push, crane looks for the credential file at:
```
$HOME/.docker/config.json
```

Podman uses a different default file location but you can override this with the --authfile flag:
```
aws ecr get-login-password --region us-west-2 | podman login --username AWS --password-stdin <ID>.dkr.ecr.us-west-2.amazonaws.com --authfile=$HOME/.docker/config.json
```

Once I had created that file, oci_push worked as expected. You might want to add this to the docs as well. Docker and Crane auth would work out-of-the-box but Podman would create this in a different location by default and fail.

**Comment by bcspragu** [comment]
Just in case someone else comes across this while trying to log in with Azure, here's the incantation I needed to get it working:

```
az acr login \
  --name <repo> \
  --expose-token \
  --output tsv --query accessToken | \
podman login \
  --username 00000000-0000-0000-0000-000000000000 \
  --password-stdin \
  --compat-auth-file=$HOME/.docker/config.json <repo>.azurecr.io
```

Not sure if the `--compat-auth-file` is a recent change or not, but podman not only uses a different file location, but a different format as well. `--compat-auth-file` uses the Docker format ([docs](https://docs.podman.io/en/latest/markdown/podman-login.1.html)). And [Azure docs](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli) for good measure.
