### ISSUE TITLE
FR: implement flatten_tars macro

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#23]
Needed to flatten multiple layers into one;

Features 

- takes multiple tar files and spits out a single flattened layer

**Comment by thesayyn** [comment]
this turned out to be super simple with pkg_tar. 

```
pkg_tar(
  name = "flatten",
  srcs = ["layer1.tar", "layer2.tar"]
)
```

**Comment by thesayyn** [comment]
closing as theres an obvious alternative.

**Comment by Place1** [comment]
I've run into this question as well but found I needed to use `deps` instead of `srcs` like this:

```
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
pkg_tar(
  name = "flatten",
  deps = ["layer1.tar", "layer2.tar"]
)
```
