### ISSUE TITLE
oci_image docs don't specify where to import it from

### ISSUE THREAD

**Issue by jmhodges** [bazel-contrib/rules_oci#233]
The [oci_image docs](https://github.com/bazel-contrib/rules_oci/blob/main/docs/image.md) don't say where these macros can be `load`ed from. I'm not sure what format y'all like for that

**Comment by alexeagle** [comment]
You might want to use our docsite, which generates load statements for all rules/macros:
https://docs.aspect.build/rules/rules_oci/docs/image#oci_image

We have avoided writing those into the hand-maintained docs because it really should be the job of the docgen pipeline.

**Comment by thesayyn** [comment]
Also all of our public api is exported  from `@rules_oci//oci:defs.bzl` except for pull which exported from `@rules_oci//oci:pull.bzl` due to technical reasons.

**Comment by alexeagle** [comment]
I guess we could just repeat what you just wrote at the top of `defs.bzl` and it will get documented on every markdown page that's derived from that file. PR coming
