### ISSUE TITLE
oci_tarball fails if called with no tags

### ISSUE THREAD

**Issue by chancila** [bazel-contrib/rules_oci#252]
this is okay:

```
oci_tarball(
    name = "image_tar",
    image = ":image",
    repo_tags = [],
)
```

this fails to build:

```
oci_tarball(
    name = "image_tar",
    image = ":image",
)
```

error:

```
	File "/Users/chancila/Snapchat/Dev/.cache/bazel/arm64/0b63180b51ef7d80cbce3ff6de02bf22/external/rules_oci/oci/private/tarball.bzl", line 60, column 20, in _tarball_impl
		ctx.actions.run(
Error in run: at index 1 of inputs, got element of type NoneType, want File
ERROR: /Users/chancila/Snapchat/Dev/snapci/bin/services/external_proxy/BUILD.bazel:46:12: Analysis of target '//bin/services/external_proxy:image_tar' failed
ERROR: Analysis of target '//bin/services/external_proxy:image_tar' failed; build aborted:
INFO: Elapsed time: 0.273s (0.00m)
```

**Comment by loopingz** [comment]
The doc https://docs.aspect.build/rules/rules_oci/docs/tarball claim it is optional and a label, while the example shows a list of string passed.

My understand is that it expect a label to a file with one line per tag and is mandatory

**Comment by thesayyn** [comment]
oci_tarball rule only accepts a file label but the oci_tarball macro which knows how to generate tags file from starlark list accepts both `label` and `list []`.

**Comment by loopingz** [comment]
Ok so change the import:

```
load("@rules_oci//oci/private:tarball.bzl", "oci_tarball")
# to
load("@rules_oci//oci:defs.bzl", "oci_tarball")
```

But repo_tags is still not optional, the default value should be moved from `None` to `[]`

**Comment by thesayyn** [comment]
> But repo_tags is still not optional, the default value should be moved from `None` to `[]`

yes, that's a bug. that said you should only imports symbols from `@rules_oci//oci:defs.bzl`

**Comment by loopingz** [comment]
I agree that importing from a private folder does not seem like a good thing, but following doc seems a safe bet normally :)

Thank you for your answers

**Comment by alexeagle** [comment]
#293 fixes the documentation bug
