### ISSUE TITLE
rules_oci does not work on linux arm64 hosts due to jq dependency

### ISSUE THREAD

**Issue by chancila** [bazel-contrib/rules_oci#253]
```
While resolving toolchains for target //bin/services/external_proxy:image: No matching toolchains found for types @aspect_bazel_lib//lib:jq_toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@aspect_bazel_lib//lib:jq_toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
```

`//bin/services/external_proxy:image` being a `oci_image` target

if this is a known issue perhaps stating compatible architectures might be handy

**Comment by chancila** [comment]
I was able to work around this issue by building my own jq arm64 binary and registering a toolchain within my workspace locally:

on a mac arm64 host:
```
docker run --rm -it ubuntu:18.04
apt update
apt upgrade
apt install git build-essential make libtool autoconf
git clone https://github.com/jqlang/jq
git submodule update --init --recursive
autoreconf -fi
./configure --with-oniguruma=builtin
make -j8
```

```starlark
load("@aspect_bazel_lib//lib/private:jq_toolchain.bzl", "jq_toolchain")

jq_toolchain(
    name = "jq_linux_arm64_tools",
    bin = ":jq", # commited prebuilt jq binary locally
)

toolchain(
    name = "jq_linux_arm64_toolchain",
    exec_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
    ],
    toolchain = ":jq_linux_arm64_tools",
    toolchain_type = "@aspect_bazel_lib//lib:jq_toolchain_type",
)
```

**Comment by malt3** [comment]
FYI: This can soon be resolved using yq since [stamping support](https://github.com/aspect-build/bazel-lib/pull/456) is coming.

**Comment by archen** [comment]
if anyone is looking for a quick patch-around, this works for my own usecases but I make no guarantees that it works with all: https://github.com/archen/rules_oci/pull/1

**Comment by michaeljs1990** [comment]
Tested out your above patch and although it looks like it might break something else based on the tests it did let me keep developing on my linux/arm64 machine. I don't think I will ever purchase another arm machine 😞

**Comment by archen** [comment]
@michaeljs1990 yeah I haven't had time to replace all of the filtration in the image.sh.tpl with yq-compat. It's funny... ARM hasn't been as painful as I thought it would be, but I sure am glad I'm using bazel to compile tools from code as needed for my dev corps instead of relying on prebuilds.

**Comment by thesayyn** [comment]
See https://github.com/bazel-contrib/rules_oci/pull/337#issuecomment-1718621054

**Comment by thesayyn** [comment]
Will be fixed by #386

**Comment by hunshcn** [comment]
When will we upgrade to bazel-lib 2.0? Is there a definite schedule? This hinders some tests (all my personal machines are arm64, linux/mac).

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/386

> When will we upgrade to bazel-lib 2.0

That will happen with the 2.x version of rules_oci, which we are already landing PRs to.
