### ISSUE TITLE
OCI Image //:image failed: not all outputs were created or valid

### ISSUE THREAD

**Issue by LouisLU9911** [bazel-contrib/rules_oci#258]
Hey guys!

I am a user of rules_docker and I am glad to switch from rules_docker to rules_oci. 😃 

I found that an example of building an image with C/C++ binaries is still needed.
So, I tried to write a [demo](https://github.com/LouisLU9911/rules_oci-cc-image-example) about it, but failed when attempting to build my image.

Here’s the error message I received:

```bash
$ git clone https://github.com/LouisLU9911/rules_oci-cc-image-example.git
$ cd rules_oci-cc-image-example/others
$ bazel build :image
Starting local Bazel server and connecting to it...
WARNING: Could not find the `$HOME/.docker/config.json` and `$XDG_RUNTIME_DIR/containers/auth.json` file.
 Running one of `podman login`, `docker login`, `crane login` may help.
INFO: Analyzed target //:image (57 packages loaded, 450 targets configured).
INFO: Found 1 target...
ERROR: /path/to/rules_oci-cc-image-example/others/BUILD.bazel:15:10: TreeArtifact image was not created
ERROR: /path/to/rules_oci-cc-image-example/others/BUILD.bazel:15:10: OCI Image //:image failed: not all outputs were created or valid
Target //:image failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 32.791s, Critical Path: 1.83s
INFO: 19 processes: 12 internal, 3 local, 4 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

I tried to figure out what went wrong:

```bash
$ ls bazel-bin/image
image
$ ls bazel-bin/image/image
blobs  index.json  oci-layout
```

It seems that the files and directories under `bazel-bin/image/image` are [what crane created](https://github.com/bazel-contrib/rules_oci/blob/v1.0.0/oci/private/image.sh.tpl#L143) and what we need, but we expected them to be under `bazel-bin/image`.

Perhaps the usage [here](https://github.com/bazel-contrib/rules_oci/blob/v1.0.0/oci/private/image.bzl#L165) is causing the problem. I’m not sure if it would accept a directory as an action’s output.

I might have missed some configurations in my example. Do you have any ideas about it? 🤔

**Comment by thesayyn** [comment]
This is no longer valid, should be fixed in 2.x

**Comment by jtszalay** [comment]
Hello!

We're trying out the rules_oci 2.0 alpha because we're really looking forward to speed improvements. Locally it works great and we do see speedups! However in our CI setup we start to see build failures.
With Bazel version: 7.1.0

With `common --remote_download_outputs=toplevel` images/tarballs/pushes work just fine.
with `common --remote_download_outputs=minimal` however we get messages like the following:
```
[2024-05-28T17:11:37Z] ERROR: /pre-merge/bazel/images/clickhouse/BUILD.bazel:46:12: TreeArtifact bazel/images/clickhouse/clickhouse_image_image was not created
[2024-05-28T17:11:37Z] ERROR: /pre-merge/bazel/images/clickhouse/BUILD.bazel:46:12: OCI Image //bazel/images/clickhouse:clickhouse_image_image failed: not all outputs were created or valid 
```

On `rules_oci 1.7.5` we didn't see errors like this in our CI.
This not all outputs were created or valid implies dangling symlinks / hardlinks

**Comment by FrankPortman** [comment]
Hi - I think we are hitting this issue as well. Did you ever come up with a workaround?
