### ISSUE TITLE
Replace shasum with sha256sum

### ISSUE THREAD

**Issue by aaliddell** [bazel-contrib/rules_oci#259]
`shasum` is a perl script that doesn't appear to be available by default on some systems (Fedora & similar for one). Since you are only using SHA256, the `sha256sum` binary (which is not a perl script) could be a better choice, provided it doesn't have its own availability concerns. From a check of OS's I have quick access to, everything has `sha256sum` but not everything has `shasum`, but I don't have a Mac etc to check.

Alternatively you could support multiple potential methods and try whichever works first: e.g. `shasum` -> `sha256sum` -> `openssl sha256`.

I can send this as a PR if you like?

edit: looking at Debian as an example: `shasum` comes from the [`perl`](https://packages.debian.org/sid/amd64/perl/filelist) package, whereas `sha256sum` comes from [`coreutils`](https://packages.debian.org/sid/amd64/coreutils/filelist) which is an essential package for every install (things such as `rm`, `cp` and also `wc` which you declare as dependency too).

**Comment by alexeagle** [comment]
using sha256sum from coreutils makes sense to me. A PR would be great, yes please :)

**Comment by thesayyn** [comment]
The problem with the `sha256sum` is it's not available on MacOS. this is likely a breaking change.

**Comment by thesayyn** [comment]
we should either use the fake toolchain selection approach to get the tool from https://github.com/aspect-build/bazel-lib/blob/6393098453db7c162fd0001c1c251f388d2c287f/docs/repositories.md#register_coreutils_toolchains or fail with a better error message suggesting some commands to fix this.

**Comment by aaliddell** [comment]
Not sure a toolchain will help here, since the usage is under repo context. Since it's only actually used once under repo context, could trying both be an option? If one fails with return code 127, try the other. Or alternately, switch the command based on OS...

**Comment by thesayyn** [comment]
trying both makes sense to me. I'd be fine with that
