### ISSUE TITLE
provide a reliable way to create python images

### ISSUE THREAD

**Issue by dudicoco** [bazel-contrib/rules_oci#262]
The provided example for creating a Python image is very complex as it requires a macro + a module for it to work:
https://github.com/aspect-build/bazel-examples/blob/main/oci_python_image/workaround_rules_pkg_153/runfiles.bzl
https://github.com/aspect-build/bazel-examples/blob/main/oci_python_image/py_image_layer.bzl

This seems like an unreliable workaround - what if the code in the example changes? Is the user supposed to watch the repository and update the code if that happens?

I believe a proper solution would be to bake this into a rule within rules_oci.

**Comment by thesayyn** [comment]
Principled fix for this is to fix rules_pkg to lay out proper runfiles trees. the macro is basically a workaround for rules_pkg not rules_oci. Then you wouldn't need all this userspace macros.

That said one of our goals for rules_oci is to not get involved in the business of providing language specific image rules. https://github.com/bazel-contrib/rules_oci#bazel-rules-for-oci-containers

**Comment by dudicoco** [comment]
@thesayyn is there an open issue for this in rules_pkg?

I see [js_image_layer](https://github.com/aspect-build/rules_js/blob/main/docs/js_image_layer.md) exists within rules_js, did you consider adding such a rules to rules_python?

**Comment by thesayyn** [comment]
js_image_layer basically a fancy pkg_tar so ideally you shouldn't need language specific generators like js_image_layer.

> did you consider adding such a rules to rules_python?

i haven't. that'd be probably maintenance burden on me/rules_oci given that rules_python has it's own problems they need to deal with.

**Comment by thesayyn** [comment]
closing this in favor of #254
