### ISSUE TITLE
Add support for basic auth

### ISSUE THREAD

**Issue by joca-bt** [bazel-contrib/rules_oci#267]
We have a docker credential helper which returns basic auth information, like so:

```
{
  "<url>": {
    "type": "basic",
    "login": "<login>",
    "password": "<password>"
  }
}
```

However, basic auth is marked as [TODO](https://github.com/bazel-contrib/rules_oci/blob/main/oci/private/download.bzl#L8). I could not find a Bazel/Starlark function to encode to base64, otherwise this would be straightforward.

Would it make sense to add a encoder/decoder of base64 to Skylib and then use that or implement it directly in this repo?

**Comment by thesayyn** [comment]
fixed by #268
