### ISSUE TITLE
Please add ability to use make variables

### ISSUE THREAD

**Issue by farcop** [bazel-contrib/rules_oci#294]
for oci_image:
   env, annotations, labels,...

for oci_push:
   image, tags, repository

for oci_tarball:
   repo_tags, image

Example code:
```
    if ctx.attr.env:
        env = {k: ctx.expand_make_variables("env", v, ctx.var) for k,v in ctx.attr.env.items()}

    if ctx.attr.annotations:
        annotations = {k: ctx.expand_make_variables("annotations", v, ctx.var) for k,v in ctx.attr.annotations.items()}
```

**Comment by thesayyn** [comment]
This should already be possible today as most of these attributes support passing a file label.  https://github.com/aspect-build/bazel-lib/blob/main/docs/expand_make_vars.md#expand_template can be used to expand variables and locations beforehand and pass it as a file to designated attribute.

```
expand_template(
 name = "env_expanded"
)

oci_image(
  env = ":env_expanded"
)
```

**Comment by farcop** [comment]
@thesayyn Unfortunately I don't understand how to do it with expand_template()

**Comment by farcop** [comment]
Let me explain a little. I am trying to migrate from `rules_docker` to `rules_oci`
With `rules_docker` I can do simple
```
container_image(
    name = "image",
    env = {
        "GA_TRACKING_ID": "$(GA_TRACKING_ID)",
        "INTERCOM_ID": "$(INTERCOM_ID)",
        "KUBLR_INTERCOM_ID": "$(INTERCOM_ID)",
    },
    toolchains = ["//:my_vars"],
)
```

I want the same behavior with `rules_oci`

**Comment by sfc-gh-ptabor** [comment]
Please see this example:
https://github.com/bazel-contrib/rules_oci/blob/main/examples/labels/BUILD.bazel

that stamps labels using (as a workaround `jq` rule).

**Comment by farcop** [comment]
@sfc-gh-ptabor Thank you!

I made ugly workaround with genrule just like this
```
genrule(
    name = "custom_env_vars",
    outs = ["custom_vars"],
    cmd = """cat <<EOF > $@
GA_TRACKING_ID=$(GA_TRACKING_ID)
INTERCOM_ID=$(INTERCOM_ID)
KUBLR_INTERCOM_ID=$(INTERCOM_ID)
EOF""",
    toolchains = ["//:kublr_vars"],
)

oci_image(
    name = "image",
    env = ":custom_env_vars",
)
```
Will wait for this issue resolve...

**Comment by sfc-gh-ptabor** [comment]
I don't think it's a workaround. It's official recommendation of this project. 
Want to make it more convenient: Write own macro that wraps this 2 rules. 

I'm not rulling out whether I like this philosophy or not, but it's what I learned with my O(3) contributions.

**Comment by thesayyn** [comment]
> I don't think it's a workaround. It's official recommendation of this project.

This is right. Closing as not planned.

**Comment by leriel** [comment]
Thanks for this thread! Just to expand above with dynamic env, an example of dynamic tag:
```
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_tarball")

genrule(
    name = "docker_tag",
    outs = ["custom_vars.txt"],
    cmd = "echo myimage:$(VERSION) > $@",
)

oci_image(
    name = "docker_image",
    base = "@base",
)

oci_tarball(
    name = "docker_tar",
    image = ":docker_image",
    repo_tags = ":docker_tag",
)

# bazel build :docker_tar --define VERSION=123
```
