### ISSUE TITLE
`oci_image` does not work with `.tar.xz` preventing `.deb` layers

### ISSUE THREAD

**Issue by mattyclarkson** [bazel-contrib/rules_oci#302]
We [specify](https://github.com/bazel-contrib/rules_oci/blob/cb312373186fab1e49708e2292f70374e294767b/oci/private/image.bzl#L52) that the `oci_image#tar` variables can accept are `.tar`, `.tar.gz` and `.tar.xz`, however, that is not the case. They _must_ be `.tar` otherwise the `crane` runtime repackages the `.tar.xz` as `.tar.xz.gz` in the blobs.

Re-using the `examples/deb` to reproduce:

```diff
diff --git a/examples/deb/BUILD.bazel b/examples/deb/BUILD.bazel
index b509608..8427606 100644
--- a/examples/deb/BUILD.bazel
+++ b/examples/deb/BUILD.bazel
@@ -1,4 +1,4 @@
-load("//oci:defs.bzl", "oci_image")
+load("//oci:defs.bzl", "oci_image", "oci_tarball")

 [
     oci_image(
@@ -12,3 +12,9 @@ load("//oci:defs.bzl", "oci_image")
         "arm64",
     ]
 ]
+
+oci_tarball(
+    name = "tarball",
+    image = ":image_amd64",
+    repo_tags = ["test:test"],
+)```

```
```
$ bazelisk run examples/deb:tarball
INFO: Running command line: bazel-bin/examples/deb/tarball.sh
f497872f8621: Loading layer [=>                                                 ]  32.77kB/1.409MB
ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header
```

The blob is stored incorrectly:

```
$ file bazel-bin/examples/deb/image_amd64/blobs/sha256/*
bazel-bin/examples/deb/image_amd64/blobs/sha256/e34708c35679dadb497aac30b61a09d7b50ed7f43dae43baadcbe68a57dff20d: gzip compressed data, max speed, original size modulo 2^32 1409104
```
```
$ cat bazel-bin/examples/deb/image_amd64/blobs/sha256/e34708c35679dadb497aac30b61a09d7b50ed7f43dae43baadcbe68a57dff20d | gunzip | tar tvJ | head -n10
drwxr-xr-x root/root         0 2022-03-27 19:40 ./
drwxr-xr-x root/root         0 2022-03-27 19:40 ./bin/
-rwxr-xr-x root/root   1234376 2022-03-27 19:40 ./bin/bash
drwxr-xr-x root/root         0 2022-03-27 19:40 ./etc/
-rw-r--r-- root/root      1994 2022-03-27 19:40 ./etc/bash.bashrc
drwxr-xr-x root/root         0 2022-03-27 19:40 ./etc/skel/
-rw-r--r-- root/root       220 2022-03-27 19:40 ./etc/skel/.bash_logout
-rw-r--r-- root/root      3526 2022-03-27 19:40 ./etc/skel/.bashrc
-rw-r--r-- root/root       807 2022-03-27 19:40 ./etc/skel/.profile
drwxr-xr-x root/root         0 2022-03-27 19:40 ./usr/
```

i.e. the runtime has taken the `.tar.xz` and put it into the blobs as `.tar.xz.gz` rather than (I assume, not an expert), just copying it as `.tar.xz`.

One can work around this by running `xz --decompress` on the `data.tar.xz` after unpacking the Debian package.

**Comment by alexeagle** [comment]
Ouch! I think we should probably change that constraint to allow only `.tar` files until we have a proper fix. Per semver that's usually a breaking change, but if we can argue that it was already broken, so no working code stops working, then it's okay.

**Comment by alexeagle** [comment]
The alternative would be to convince the `crane` maintainers that it should accept compressed tarfiles and do the right thing with them. Maybe @jonjohnsonjr can give us some guidance on which way to go.
