### ISSUE TITLE
Provide a PushInfo provider in oci_push

### ISSUE THREAD

**Issue by opicaud** [bazel-contrib/rules_oci#318]
Hey all,

We are currently migrating `rules_helm`to support `rules_oci` from `rules_docker`, see [#12](https://github.com/abrisco/rules_helm/issues/12) currently it is using this provider: 

```
# A provider containing information exposed by container_push rules
PushInfo = provider(fields = [
    "registry",
    "repository",
    "digest",
])
```
Would it be possble to get such as kind of provider from `oci_push` rules ?

Thanks 

Olivier

**Comment by thesayyn** [comment]
Please see https://github.com/bazel-contrib/rules_oci/pull/244#issuecomment-1575654791

**Comment by opicaud** [comment]
Thanks @thesayyn, I close this one and jum to [#244](https://github.com/bazel-contrib/rules_oci/pull/244#issuecomment-1575654791)
