### ISSUE TITLE
Build base images from Dockerfile's

### ISSUE THREAD

**Issue by kriscfoster** [bazel-contrib/rules_oci#321]
Is there a way to dynamically create images from a `Dockerfile` with `rules_oci`?

We were doing this before with `rules_docker` in [this](https://github.com/kriscfoster/multi-language-bazel-monorepo/blob/main/WORKSPACE.bazel#L143-L146) way.

The use-case is that we pull a common base image from the registry & all images we build in the repository all start with that base image. However, some of them extend it by doing things like `yum install -y helm`.

**Comment by thesayyn** [comment]
duplicate of #35
