### ISSUE TITLE
1.3.0 release is breaking js_image_layer

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#334]
https://github.com/bazel-contrib/rules_oci/pull/313 removes support for `.tar.gz` file extensions, but rules_js produces them 
https://github.com/aspect-build/rules_js/blob/main/js/private/js_image_layer.bzl#L230

#313 says

> Non-tar files never actually worked here

But this test has been passing https://github.com/aspect-build/rules_js/blob/main/e2e/js_image_oci/src/test.yaml#L6 so I think that may be incorrect, and we should just revert #313.

FYI @mattyclarkson as this originated from #302

**Comment by mattyclarkson** [comment]
My issue was with `.tar.xz`, so it's likely it recognises `.tar.gz` as that's what it compresses the layers to anyway.
