### ISSUE TITLE
Ability to 'disable' an entrypoint in a base image (override to [])

### ISSUE THREAD

**Issue by sfc-gh-ptabor** [bazel-contrib/rules_oci#336]
I have a base image that has 'entrypoint' set. 

I would like to use 'oci_image' to override the entrypoint to `[]`. 

but If I try, to do: 

```
  oci_image(
    ...
    entrypoint=[],
    ...
  )
```
The image stays as is... as the empty entrypoint is ignored: 

https://github.com/bazel-contrib/rules_oci/blob/59a054627c6bee6100cab5614f6183c142218998/oci/private/image.bzl#L150-L151

I think that nice solution depends on:  https://github.com/bazelbuild/bazel/issues/14434

But I think it could be worked around by declaring:

```
"entrypoint": attr.string_list(doc = "A list of arguments to use as the `command` to execute when the container starts. These values act as defaults and may be replaced by an entrypoint specified when creating a container.",
  default=["#magic-ignored-entrypoint#"]),
```

**Comment by thesayyn** [comment]
There's a workaround for this, if you provide an empty file to `entrypoint`, oci_image will set entrypoint to `[]`
