### ISSUE TITLE
Runtime of oci_image is proportional to the total size of of all tars plus the base image

### ISSUE THREAD

**Issue by wskinner-dd** [bazel-contrib/rules_oci#365]
The time required to build `oci_image` seems to be proportional to the total size of the tars plus the size of the base image. This was surprising to me. I expected `oci_image` to take time proportional to the size of only the modified or added layers. After reading through the source code and running some tests, it seems like the reason for this may have something to do with [crane mutate](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_mutate.md). 

Are these runtime characteristics an intended or necessary property of `rules_oci` or the OCI spec? Or are they due to implementation details of `rules_oci` and its dependencies like `crane`?

# How to reproduce the issue
I tested this behavior by comparing the build time of four scenarios:
1. An image with a 21GB base image, one 3.6GB layer and one tiny layer.
2. An image with a 21GB base and one tiny layer.
3. An image with a 1GB base, one 3.6GB layer and one tiny layer.
4. An image with a 1GB base and one tiny layer.

For both scenarios, I built the target, then modified `app.py` and measured the time required to build again.

```
$ bazel build //:two_layer_big_image
INFO: Elapsed time: 58.190s, Critical Path: 58.13s

$ bazel build //:one_layer_big_image
INFO: Elapsed time: 21.697s, Critical Path: 21.65s

$ bazel build //:two_layer_small_image
INFO: Elapsed time: 48.928s, Critical Path: 48.88s

$ bazel build //:one_layer_small_image
INFO: Elapsed time: 1.089s, Critical Path: 1.04s 
```

# BUILD
```
pkg_tar(
    name = "app_tar",
    srcs = ["//:app.py"],
)

pkg_tar(
    name = "big_file",
    srcs = ["//:ubuntu-22.04.3-desktop-amd64.iso"],
)

oci_image(
    name = "two_layer_small_image",
    base = "@python_311",
    tars = [
        ":big_file",
        ":app_tar",
    ],
)

oci_image(
    name = "one_layer_small_image",
    base = "@python_311",
    tars = [
        ":app_tar",
    ],
)

oci_image(
    name = "two_layer_big_image",
    base = "@nct_image",
    tars = [
        ":big_file",
        ":app_tar",
    ],
)

oci_image(
    name = "one_layer_big_image",
    base = "@nct_image",
    tars = [
        ":app_tar",
    ],
)
```

**Comment by wskinner-dd** [comment]
After reading through the source code, I think I understand the reason this is slower than I expected. Building an `oci_image` basically does four things:
- `crane push`
- `crane mutate --append <tar 1> --append <tar 2> ... --append <tar n>`
- `crane config`
- `crane pull`

I wonder if there may be room to speed up the `push` and `mutate` steps. If zot's blob cache can be reused across build invocations, `push` becomes nearly instantaneous (this won't work for `crane` registries).

For `crane mutate`, it should in theory be possible to append each layer in order and cache the results. So if tar n changes, we could just append it to the cached result of a previous `crane mutate --append <tar n - 1>`.

**Comment by thesayyn** [comment]
https://github.com/bazel-contrib/rules_oci/pull/324 is gonna solve this. I can't continue my work on that right now, packed with other stuff.

**Comment by thesayyn** [comment]
Blocked by https://github.com/bazelbuild/bazel/issues/20891

**Comment by thesayyn** [comment]
Working on it at https://github.com/bazelbuild/bazel/pull/21263

**Comment by thesayyn** [comment]
this is fixed by combination of #560 #559 #558

**Comment by thesayyn** [comment]
It's very possible that we broke something, could you please file an issue with a reproducer? i'd like to take a look

**Comment by thesayyn** [comment]
> Is this an appropriate fix or am I doing something wrong on my end?

Principled fix is here: https://github.com/bazel-contrib/rules_oci/pull/567
