### ISSUE TITLE
Unable to authenticate against ECR using amazon-ecr-credential-helper

### ISSUE THREAD

**Issue by BigForNothing** [bazel-contrib/rules_oci#388]
I am required to use aws sso to login (`aws sso login` via CLI), and I also use the [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper). My `~/.docker/config.json` looks like this

```
{
        "credsStore": "ecr-login"
}
```
After doing the sso login, `docker pull image` works just fine when I'm pulling from the private ECR registry, but I am still getting the 401 when I use the oci_pull rules. 

If I remove the `credsStore` line from the `config.json`, then login following the [instructions here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html), the oci_pull works fine. 

It appears the credential helper isn't supported even though this [comment](https://github.com/bazel-contrib/rules_oci/issues/353#issuecomment-1719955082) says 
>  if docker pull works, then oci_pull should too

Also this is somewhat related to the auth issue in #353 but since that is closed and this issue appears to be a credential-helper issue, I'm creating a new issue.

**Comment by alexeagle** [comment]
I think at minimum we are missing some documentation for the credential helper, along with a couple examples.

**Comment by nchepanov** [comment]
I'm seeing this too. I previously had just this `{"credsStore": "ecr-login"}` in my `~/.docker/config.json`. This was sufficient for both Docker Desktop on macos as well as docker daemon on Ubuntu to recognize ECR.

This is consistent with the official [amazon-ecr-credential-helper documentation](https://github.com/awslabs/amazon-ecr-credential-helper?tab=readme-ov-file#docker). This is the minimal setup that should be sufficient.

This setup however is not sufficient for `oci_pull` to work.

The implementation first checks for `credHelpers` key and if not found looks into `auths`. It never checks top level  `credsStore` key: 
https://github.com/bazel-contrib/rules_oci/blob/c9c8b070f131986a6461d79fe75578778dc251e6/oci/private/pull.bzl#L83

The workaround for me was to add the following section in addition to `"credsStore": "ecr-login"`:

```json
	"credHelpers": {
		"public.ecr.aws": "ecr-login",
		"<aws_account_id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
	}
```

I think the current implementation is incomplete.

**Comment by thesayyn** [comment]
We do use credsstore key, it is used only when auths contains a key for the host but has no value. 
https://github.com/bazel-contrib/rules_oci/blob/c9c8b070f131986a6461d79fe75578778dc251e6/oci/private/pull.bzl#L107-L109

**Comment by hjkatz** [comment]
@thesayyn That is not a solution for the problem at hand. How can we use `rules_oci` to pull from a private ECR with credentials defined by the `amazon-ecr-credential-helper`?

**Comment by mazzy89** [comment]
What Bazel OCI Pull rule does underneath is to run the following bash executable:

```bash
#!/usr/bin/env bash

exec "docker-credential-ecr-login" get <<< "$1"
```

where `$1` is the registry URL in the format `<accound-id>.dkr.ecr.<region>.amazonaws.com`

In my case the docker config looks like

```json
{
	"auths": {
		"<account-id>.dkr.ecr.<region>.amazonaws.com": {}
	},
	"credsStore": "ecr-login",
	"credHelpers": {
		"<account-id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
	}
}
```

I had to set up the `AWS_PROFILE` because I was not using the default one but after done it worked like a charm.
