### ISSUE TITLE
Enhance the semantic tracking of oci_pull to facilitate its integration with tools such as Renovate

### ISSUE THREAD

**Issue by ns-ggeorgiev** [bazel-contrib/rules_oci#391]
At a cursory look, "tag" and "digest" might appear synonymous, especially in the context of the build process. However, when we delve into source code maintenance tools such as Renovate, distinctions become evident. Tools like Renovate necessitate semantic versioning data, which demands a tag. However, this implies that the code settles for a non-reproducible build setup. This is because within the Docker community, the idea of mutable or 'floating' tags is widely embraced, allowing tag artifacts to change over time.

To demonstrate why relying solely on digest is inadequate, consider wanting to lock a specific image to the ubuntu:20.04 updates. With Renovate, it's feasible to configure major and minor updates for this dependency to be ignored. Yet, if described by digest alone, this becomes unachievable.

Worth noting is that although the convention of floating tags is widely recognized, there's also substantial backing for immutability. Many teams lean towards its adoption. Our aim is likely to find a solution that accommodates both these paradigms harmoniously.

Here's what I'm proposing, which also retains backward compatibility:

1. Allow simultaneous use of tag and digest, adhering to the following logic:

```
tag      | digest   | reproducible | action
provided | n/a      | TRUE         | warning: tags are not reproducible
provided | n/a      | FALSE        |  
n/a      | provided | TRUE         |  
n/a      | provided | FALSE        | warning: digest do not follow the semantic update
provided | provided | TRUE         | if tag != digest; warning; using digest that does not match the tag
provided | provided | FALSE        | if tag != digest; warning; using tag that does not match the digest
```

2. When both are provided convert the digest to a locking mechanism, similar to hashes in requirements.txt in python. Say add a new flag `strict` that when true, converts the warnings into errors.

**Comment by gzm0** [comment]
Any reason not to default to failing in case tag and digest do not match?

**Comment by ns-ggeorgiev** [comment]
> Any reason not to default to failing in case tag and digest do not match?

no reason, it is probably the best option, but if I remember correctly there was some reservation about it, this is I proposed to be optional. If you asking me, matching expectation should be by default.

**Comment by gzm0** [comment]
:facepalm: I realized why: Docker tags are *mutable* so this would mean your build suddenly fails because someone published a new image to the tag (and the build would keep failing until the digest gets updated).

**Comment by mark-thm** [comment]
> I am coming back to this, i believe the current solution is to allow both tag and digest to be provided, and prefer digest over tag if both are provided. Anybody wants to make that change and send a PR?

Pushed #587 to allow setting both tag and digest together.

In terms of upgrade automation, I think there'd still be a chunk of work associated with actually adding Renovate support -- parsing Starlark in regex to do the update is likely far from easy, so the MODULE.bazel manager would need to be updated to be taught explicitly about rules_oci's extensions and the relevant docker manager configured to deal with the findings.

In the meantime, one path my organization is likely to go down is to spec a simple JSON lockfile which will contain all the image details and to teach a standalone CLI to update the images according to our own tagging rules. We have similar standalone CLIs already and while they're easier to customize, they're also annoyingly less general or pervasive than Renovate.

**Comment by gzm0** [comment]
At least for non-bzlmod, this is already in place:

https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/bazel/rules/oci.ts

The same for rules_docker:

https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/bazel/rules/docker.ts

I do not know what the state of support for bzlmod extensions in Renovate is.

**Comment by gzm0** [comment]
For reference: PR for oci.pull support in Renovate: https://github.com/renovatebot/renovate/pull/32453
