### ISSUE TITLE
oci_pull gets 401 Unauthorized on curl.

### ISSUE THREAD

**Issue by tonyliao-mineral** [bazel-contrib/rules_oci#396]
I want to build an Apache Beam SDK image like this:

```
oci_image(
    name = "move_data_worker_image",
    base = "@beam_python",
    entrypoint = [
        "/opt/apache/beam/boot",
    ],
    tars = [":move_data_layer"],
)
```
where the base image comes from my WORKSPACE:

```
# https://hub.docker.com/r/apache/beam_python3.10_sdk/tags
oci_pull(
    name = "beam_python",
    # 2.51.0
    digest = "sha256:af507ee3b2fc7e0ad154c9c0caafdc3c3191886cce36943f40c8f91e776f117e",
    image = "index.docker.io/library/apache/beam_python3.10_sdk",
    # registry = "registry.hub.docker.com",
    # repository = "apache/beam_python3.10_sdk",
)
```
I was able to do docker pull apache/beam_python3.10_sdk:2.51.0 on the command line. But during Bazel build I get a really weird error:

@beam_python//:beam_python depends on @beam_python_single//:beam_python_single in 
repository @beam_python_single which failed to fetch. no such package '@beam_python_single//': 
curl https://index.docker.io/v2/library/apache/beam_python3.10_sdk/manifests/sha256:af507ee3b2
fc7e0ad154c9c0caafdc3c3191886cce36943f40c8f91e776f117e returned non-success status code 401
On some research I found this un-answered stack post: [Bazel's container_pull failing to pull aws-cli image](https://stackoverflow.com/questions/74900837/bazels-container-pull-failing-to-pull-aws-cli-image) which has very similar errors. There are also https://github.com/bazel-contrib/rules_oci/issues/284 that seems to have a similar but different issue. So it seems like it's not Beam related. I'm wondering if anyone has seen this before. Thanks!

**Comment by tonyliao-mineral** [comment]
Update: falling back to rules_docker's `container_pull` with the exact same input works fine: 
# https://hub.docker.com/r/apache/beam_python3.10_sdk/tags
```
container_pull(
    name = "beam_python",
    # 2.51.0
    digest = "sha256:af507ee3b2fc7e0ad154c9c0caafdc3c3191886cce36943f40c8f91e776f117e",
    registry = "registry.hub.docker.com",
    repository = "apache/beam_python3.10_sdk",
)
```

**Comment by ihavespoons** [comment]
I've got exactly the same issue but with the added confounding factor that it works after 1 or 2 retries.

Here are some example rules that are experiencing the issue:

` oci_pull(
        name = "coredns_1_10_1_oci_amd64",
        digest = "sha256:be7652ce0b43b1339f3d14d9b14af9f588578011092c1f7893bd55432d83a378",
        image = "docker.io/coredns/coredns",
    )

                
    oci_pull(
        name = "coredns_1_10_1_oci_arm64",
        digest = "sha256:74130b944396a0b0ca9af923ee6e03b08a35d98fc1bbaef4e35cf9acc5599105",
        image = "docker.io/coredns/coredns",
    )`

Error here:
`

WARNING: Could not fetch the manifest. Either there was an authentication issue or trying to pull an image with OCI image media types.
--
  | 2023-10-19 02:52:18 UTC | Falling back to using `curl`. See https://github.com/bazelbuild/bazel/issues/17829 for the context.
  | 2023-10-19 02:52:18 UTC | WARNING: Could not fetch the manifest. Either there was an authentication issue or trying to pull an image with OCI image media types.
  | 2023-10-19 02:52:18 UTC | Falling back to using `curl`. See https://github.com/bazelbuild/bazel/issues/17829 for the context.
  | 2023-10-19 02:52:19 UTC | INFO: Repository memcached_1_6_21-alpine3_18_oci_amd64_single instantiated at:
  | 2023-10-19 02:52:19 UTC | /var/lib/buildkite-agent/builds/canva__container-build/WORKSPACE:189:17: in <toplevel>
  | 2023-10-19 02:52:19 UTC | /var/lib/buildkite-agent/builds/canva__container-build/containers_oci/base_images.bzl:9:13: in oci_repositories
  | 2023-10-19 02:52:19 UTC | /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/pull.bzl:134:18: in oci_pull
  | 2023-10-19 02:52:19 UTC | Repository rule oci_pull defined at:
  | 2023-10-19 02:52:19 UTC | /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/pull.bzl:427:27: in <toplevel>
  | 2023-10-19 02:52:19 UTC | WARNING: Download from https://index.docker.io/v2/library/memcached/manifests/sha256:27fe55ab0ecba9a8d3ddd67b823da4f1727d10eb46d36ab5af7e693421ebdb4f failed: class java.io.FileNotFoundException GET returned 404 Not Found
  | 2023-10-19 02:52:19 UTC | ERROR: An error occurred during the fetch of repository 'memcached_1_6_21-alpine3_18_oci_amd64_single':
  | 2023-10-19 02:52:19 UTC | Traceback (most recent call last):
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/pull.bzl", line 378, column 57, in _oci_pull_impl
  | 2023-10-19 02:52:19 UTC | mf, mf_len, mf_digest = downloader.download_manifest(rctx.attr.identifier, "manifest.json")
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/pull.bzl", line 319, column 74, in lambda
  | 2023-10-19 02:52:19 UTC | download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/pull.bzl", line 295, column 48, in _download_manifest
  | 2023-10-19 02:52:19 UTC | digest = "sha256:{}".format(util.sha256(rctx, output))
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/util.bzl", line 65, column 13, in _sha256
  | 2023-10-19 02:52:19 UTC | fail(msg)
  | 2023-10-19 02:52:19 UTC | Error in fail: sha256 failed:
  | 2023-10-19 02:52:19 UTC | STDOUT:
  | 2023-10-19 02:52:19 UTC |  
  | 2023-10-19 02:52:19 UTC | STDERR:
  | 2023-10-19 02:52:19 UTC | src/main/tools/process-wrapper-legacy.cc:80: "execvp(shasum, ...)": No such file or directory
  | 2023-10-19 02:52:19 UTC | ERROR: /var/lib/buildkite-agent/builds/canva__container-build/WORKSPACE:189:17: fetching oci_pull rule //external:memcached_1_6_21-alpine3_18_oci_amd64_single: Traceback (most recent call last):
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/pull.bzl", line 378, column 57, in _oci_pull_impl
  | 2023-10-19 02:52:19 UTC | mf, mf_len, mf_digest = downloader.download_manifest(rctx.attr.identifier, "manifest.json")
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/pull.bzl", line 319, column 74, in lambda
  | 2023-10-19 02:52:19 UTC | download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/pull.bzl", line 295, column 48, in _download_manifest
  | 2023-10-19 02:52:19 UTC | digest = "sha256:{}".format(util.sha256(rctx, output))
  | 2023-10-19 02:52:19 UTC | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/rules_oci/oci/private/util.bzl", line 65, column 13, in _sha256
  | 2023-10-19 02:52:19 UTC | fail(msg)
  | 2023-10-19 02:52:19 UTC | Error in fail: sha256 failed:
  | 2023-10-19 02:52:19 UTC | STDOUT:
  | 2023-10-19 02:52:19 UTC |  
  | 2023-10-19 02:52:19 UTC | STDERR:
  | 2023-10-19 02:52:19 UTC | src/main/tools/process-wrapper-legacy.cc:80: "execvp(shasum, ...)": No such file or directory
  | 2023-10-19 02:52:19 UTC | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8864190cf1ed9e5f395c9bf8330021fb/external/memcached_1_6_21-alpine3_18_oci_amd64/BUILD.bazel:1:6: @memcached_1_6_21-alpine3_18_oci_amd64//:memcached_1_6_21-alpine3_18_oci_amd64 depends on @memcached_1_6_21-alpine3_18_oci_amd64_single//:memcached_1_6_21-alpine3_18_oci_amd64_single in repository @memcached_1_6_21-alpine3_18_oci_amd64_single which failed to fetch. no such package '@memcached_1_6_21-alpine3_18_oci_amd64_single//': sha256 failed:
  | 2023-10-19 02:52:19 UTC | STDOUT:
  | 2023-10-19 02:52:19 UTC |  
  | 2023-10-19 02:52:19 UTC | STDERR:
  | 2023-10-19 02:52:19 UTC | src/main/tools/process-wrapper-legacy.cc:80: "execvp(shasum, ...)": No such file or directory
  | 2023-10-19 02:52:19 UTC | ERROR: Analysis of target '//containers_oci/memcached:container_oci_1_6_21-alpine3_18' failed; build aborted:
  | 2023-10-19 02:52:19 UTC | INFO: Elapsed time: 9.651s
  | 2023-10-19 02:52:19 UTC | INFO: 0 processes.
  | 2023-10-19 02:52:19 UTC | FAILED: Build did NOT complete successfully (62 packages loaded, 316 targets c\
  | 2023-10-19 02:52:19 UTC | onfigured)
  | 2023-10-19 02:52:19 UTC | currently loading: @bazel_tools//src/conditions
  | 2023-10-19 02:52:19 UTC | Fetching ...sitory @memcached_1_6_21-alpine3_18_oci_arm64_single; starting

`

**Comment by alexeagle** [comment]
I think the translation is incorrect. 

```
    registry = "registry.hub.docker.com",
    repository = "apache/beam_python3.10_sdk",
``` 

-> `index.docker.io/apache/beam_python3.10_sdk`

You have an extra `/library/` segment in your non-working example, which is only used for containers that don't have a namespace IIUC

**Comment by gfrankliu** [comment]
Based on https://github.com/bazel-contrib/rules_oci/issues/301 , the extra `library` is required.
