### ISSUE TITLE
Allow config_path to be passed by the user

### ISSUE THREAD

**Issue by siddharthab** [bazel-contrib/rules_oci#412]
I have a checked-in docker config to make it hermetic for my users, but auth_config_locator currently does not allow users to specify labels as a config. The only handle they have is environment variables. So my workaround becomes to put this in my .bazelrc.

```
build --repo_env=DOCKER_CONFIG=../../execroot/__main__/bazel/docker
```

Would be nice to specify a label directly instead in MODULE.bazel.

**Comment by thesayyn** [comment]
Hmm, I have added `config_path` specifically for this but it seems it can't be overridden as oci_pull is behind a macro.  https://github.com/bazel-contrib/rules_oci/blob/35a2baf586d2f30c332a566e71d0c8f0908acb10/oci/private/pull.bzl#L32-L36
