### ISSUE TITLE
1.4.2 gives network errors with crane on MacOS

### ISSUE THREAD

**Issue by ewhauser** [bazel-contrib/rules_oci#418]
Getting the following warning when using v1.4.2:

<img width="261" alt="Screenshot 2023-11-19 at 1 52 47 PM" src="https://github.com/bazel-contrib/rules_oci/assets/131389/a3f4685a-637a-4649-a755-032e3484ffe1">

This issues did not exist in 1.4.1.  This seems to be an issue in `v0.16.1` of crane: https://github.com/bazel-contrib/rules_oci/pull/414

**Comment by ewhauser** [comment]
Tracked down to: https://github.com/google/go-containerregistry/pull/1746

**Comment by thesayyn** [comment]
Good job @ewhauser. Sent a patch https://github.com/google/go-containerregistry/pull/1848

**Comment by thesayyn** [comment]
Fix for this already in crane and we mirrored the fix. However we still need to update the launcher to listen on loopback address.
