### ISSUE TITLE
`crane registry serve` daemons are not cleaned up

### ISSUE THREAD

**Issue by malt3** [bazel-contrib/rules_oci#419]
When executing build actions locally, `crane registry serve` processes are cleaned up after a `bazel build`.
However, when using remote execution (in my case with buildbarn), `crane registry serve` processes survive between actions and pile up over time on the remote executor. This results in hundreds of processes and will starve the host of memory over multiple days.

## How to reproduce

- [setup a buildbarn cluster](https://github.com/buildbarn/bb-deployments) (for example using the docker-compose setup)
- Use the buildbarn cluster for remote execution (`--remote_executor=...`)
- use rules_oci to build container images
- Look at the running processes after the build is complete

### Expected behavior

`crane registry serve` should no longer run

### Actual behavior

`crane registry serve` processes are still running

**Comment by alexeagle** [comment]
Hm, do you think this is a bug in rules_oci, or a problem with how buildbarn terminates the worker process?

Based on 5 thumbs up I'm inclined to believe it's a bug, somewhere we get a process terminated and trap the signal, or fail to propagate the signal. Perhaps we need to explicitly use a process group somewhere?

We'll probably need help to troubleshoot this.

**Comment by malt3** [comment]
I’m not entirely sure what’s happening, but my current understanding is this:
When running builds locally (only using Bazel to run build actions), sandboxing (or some other mechanism of Bazel) cleans up processes spawned by actions.
For some reason, this doesn’t work in buildbarn (maybe because it doesn’t try to perform per-action sandboxing).
This is combined with the design of buildbarn, where workers are long-living.

The thing that confuses me here is that, by my investigation, it seems that for a large-ish monorepo that I’m testing this on, the crane/zot registry is the only process that is leaking. This makes me think that it might be a convention in Bazel to clean up any spawned processes if you are writing rules?
