### ISSUE TITLE
Migrating from @io_bazel_rules_docker//contrib:passwd.bzl

### ISSUE THREAD

**Issue by OscarVanL** [bazel-contrib/rules_oci#428]
Hi,

I'm trying to upgrade from rules_docker but about to give up as it is beyond my technical abilities and quite undocumented.

For example, I can't see a meaningful replacement for `passwd.bzl`.

The bazel tech debt I have related has `passwd_entry` and `passwd_file` that are installed from a tar during the container build process to create some users in the container. How do I replace this with `rules_oci`?

```
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("@io_bazel_rules_docker//contrib:passwd.bzl", "passwd_entry", "passwd_file")

# Create a passwd file with a root and nonroot user and uid.
passwd_entry(
    name = "passwd_root",
    gid = 0,
    uid = 0,
    username = "root",
)

passwd_entry(
    name = "passwd_nonroot",
    info = "nonroot",
    uid = 1001,
    username = "nonroot",
)

passwd_file(
    name = "passwd",
    entries = [
        ":passwd_root",
        ":passwd_nonroot",
    ],
)

pkg_tar(
    name = "passwd_tar",
    srcs = [":passwd"],
    mode = "0o644",
    package_dir = "etc",
    visibility = ["//visibility:public"],
)
```

I'm currently stumped.

**Comment by thesayyn** [comment]
Hey, we are working on rules_distroless that has this rule, https://github.com/GoogleContainerTools/rules_distroless/blob/2db6073aebd6d2cc6ee186574387892b6b1238f7/examples/passwd/BUILD.bazel#L5-L17

Given that these rules are linux specific and not at all related to building containers, we are going to host them there.

**Comment by prestonvanloon** [comment]
I'm also running into various issues with this and unable to get rules_distroless to work. 
Could you add an example to this repo? It's fairly common and even referenced in a few places with passwd.tar 

https://github.com/bazel-contrib/rules_oci/blob/375e5dbf3b2c50e83c9df0d0dc16a027984dab77/docs/image.md?plain=1#L36

**Comment by thesayyn** [comment]
> I'm also running into various issues with this and unable to get rules_distroless to work.

This is out of scope for rules_oci. Can you please file an issue in rules_distroless instead?
