### ISSUE TITLE
oci_image uses significantly more disk space than container_image from rules_docker

### ISSUE THREAD

**Issue by SanjayVas** [bazel-contrib/rules_oci#439]
`oci_image` appears to copy all base image layer blobs to its Bazel output tree. Additionally it temporarily takes up even more space due to running a separate registry for each target.

I believe `container_image` from `rules_docker` only has the created layer(s) in its output.

Anecdotally, this blew up my CI. My compressed Bazel output cache went from ~3 GiB to ~20 GiB when migrating from rules_docker to rules_oci.

**Comment by alexeagle** [comment]
I think this is fixed by that #440 - @SanjayVas if you have time, could you patch that in and verify?

**Comment by thesayyn** [comment]
@alexeagle partially. we still copy blobs from base image (copy_to_directory) into oci_image's oci-layout (treeartifact) which causes duplication of the blobs. 
we should symlink blobs from base image into the oci_image's output to prevent copies.

**Comment by thesayyn** [comment]
but that's a bigger fix and i don't have time to contribute. happy to review if somebody else is willing to contribute it.

**Comment by SanjayVas** [comment]
> I think this is fixed by that #440 - @SanjayVas if you have time, could you patch that in and verify?

Sorry, the migration to rules_oci was prefactoring for migrating our tree of repos to Bzlmod. I can possibly try after that is done, but it will of course be easier if a version with that change has been published to BCR.

**Comment by thesayyn** [comment]
Okay now that https://github.com/bazel-contrib/rules_oci/pull/560 https://github.com/bazel-contrib/rules_oci/pull/559 landed, this can be closed.
