### ISSUE TITLE
Pulling images from artifactory

### ISSUE THREAD

**Issue by UebelAndre** [bazel-contrib/rules_oci#451]
Has anyone tried to use `oci_pull` pointing to an [Artifactory](https://jfrog.com/artifactory/) instance?

**Comment by farcop** [comment]
@UebelAndre It’s better to ask a specific question right away. You tried and got some trouble?

**Comment by UebelAndre** [comment]
> @UebelAndre It’s better to ask a specific question right away. You tried and got some trouble?

What's the equivalent to

```starlark
container_pull(
    name = "linux",
    digest = "sha256:###########################################",
    repository = "it-docker.art.company.corp"
    repository = "itsec/linux-ubuntu"
)
```

**Comment by thesayyn** [comment]
We use Bazel's http downloader to fetch everything. You can use https://bazel.build/reference/command-line-reference#flag--experimental_downloader_config to fetch through artifactory.

**Comment by UebelAndre** [comment]
Can you show me the 1-1 with the api from the deprecated repo?

**Comment by thesayyn** [comment]
I don't think I can as rules_docker used a custom go binary to pull images whereas rules_oci uses Bazel's downloader. @alexeagle wrote an article about this https://blog.aspect.dev/configuring-bazels-downloader

**Comment by thesayyn** [comment]
Something like this should work if you are fetching from dockerhub.

```
rewrite (index.docker.io)/(.*) artifactory.internal.net/artifactory/docker/$1
```

**Comment by UebelAndre** [comment]
Surely if I mirror an image from dockerhub I’d be able to use these rules to fetch it through an artifactory mirror, right? It doesn’t need to be exact but I’d unclear what the previous api would roughly translate to in order to fetch it.

**Comment by thesayyn** [comment]
Yes, as I said we don't have a custom downloader and simply using `rctx.download` to fetch everything (except the curl fallback) from the registry.  So it you have your artifactory configured right (i don't know what that means as i haven't used artficatory before) you should be able to pull through your artifactory instance as bazel will rewrite URLs oci_pull generates to one that you provide.

**Comment by thesayyn** [comment]
I'd appreciate if you could send a PR to include this in oci_pull documentation if/when you make it work.

**Comment by UebelAndre** [comment]
Sorry, not trying to be difficult I just genuinely don't understand what to do. I think it's great the rules use the bazel downloader, but what do I fill into `oci_pull` to get an artifactory image to work? Is it the exact same thing?
```starlark
oci_pull(
    name = "linux",
    # TODO: What comes next?
)
```

**Comment by thesayyn** [comment]
I believe if you are trying to fetch `ubuntu:latest` from docker hub;

1)- You wanna keep it that (eg, you don't wanna change the url) way but tell Bazel to download that image from Artifactory; 

WORKSPACE
```
container_pull(
    name = "ubuntu",
    image = "ubuntu:latest"
    digest = "sha256:deadbeef",
)
```

Rewrite config (something like this)
```
rewrite (index.docker.io)/(.*) artifactory.internal.net/artifactory/docker/$1
```

2)- You don't want to deal with rewrite and simply download from artifactory.

WORKSPACE
```
container_pull(
    name = "ubuntu",
    registry = "internal.artifactory/docker",
    repository = "ubuntu",
    digest = "sha256:deadbeef",
)
```

is what you are asking?

**Comment by thesayyn** [comment]
https://github.com/bazel-contrib/rules_oci/blob/main/docs/pull.md lists every attribute that rules_oci supports and https://docs.aspect.build/guides/rules_oci_migration might be helpful is wanna see how it compares to rules_docker.

**Comment by thesayyn** [comment]
@UebelAndre does this answer your question?

**Comment by alexeagle** [comment]
Also to be clear, rules_docker is archived because it's unmaintained, not because we promise to provide feature parity for everyone to migrate away from it. If someone stepped up to do the maintenance work, it could be unarchived.

**Comment by UebelAndre** [comment]
> @UebelAndre does this answer your question?

Yeah thanks, the info I was looking for was more or less "yeah, the rules work with Artifactory. The interface is pretty much the same but if you're having issues you might want to check your auth".
