### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#456]
It's been almost a year since we released the [1.0](https://github.com/bazel-contrib/rules_oci/releases/tag/v1.0.0), and now it's time for us to make breaking changes we have been holding back for more than 6 months.

Breaking changes that we are planning.

- Under consideration: drop zot as a registry toolchain and only support `crane registry`
- Drop  curl fallback for oci_pull, now that https://github.com/bazelbuild/bazel/pull/19501 is fixed. 
- Drop bazel 5 altogether. 
- Drop yq as a dependency.
- Start using bsdtar toolchain from bazel-lib for hermeticity.
- Upgrade bazel-lib to 2.0

**Comment by alexeagle** [comment]
Target date ought to be about a year from 1.0.0, so that's not until May, plenty of time for some Beta releases and a long RC period.

We'll have to drop support for Bazel <7.1 for users who need custom headers, though I guess we can still say Bazel 6 and Bazel 7.0 are good enough if you weren't relying on the `curl` fallback.

**Comment by thesayyn** [comment]
We are also designing a registryless version of rules_oci which will be significantly faster compared to the current design.

**Comment by siddharthab** [comment]
> registryless version of rules_oci 2.0

This will be very appreciated. Our (bioinformatics/ML) images tend to be very big, and moving from rules_docker to rules_oci, the registry roundabout was the most significant pain we felt.

**Comment by thesayyn** [comment]
Design doc for 2.0 redesign of OCI Image is here: https://docs.google.com/document/d/1wZEB9QFxyrydhLiafYbaJ0D7Jd2FZRZjvoTtx0B8-yY

**Comment by thesayyn** [comment]
As of today everything in the list above is done.

**Comment by prestonvanloon** [comment]
Since 2.0 has been released and the curl fallback has been removed. What is the workaround for pulling images via oci_pull without any docker credentials?
