### ISSUE TITLE
add docker.elastic.co to the map of known registries

### ISSUE THREAD

**Issue by cristifalcas** [bazel-contrib/rules_oci#463]
Hi,

Can we add the `docker.elastic.co` registry to the `_WWW_AUTH` map?
If I don't have this bit, pulling images doesn't work for me:

```py
    "docker.elastic.co": {
        "realm": "docker-auth.elastic.co/auth",
        "scope": "repository:{repository}:pull",
        "service": "token-service",
    },
```

**Comment by thesayyn** [comment]
PR's are welcome.

**Comment by cristifalcas** [comment]
Wonderful, I'll make one.
I just wanted to be sure it's nothing from my side
