### ISSUE TITLE
Mismatch between .json.sha256 and sha256 when loaded via tarball to Docker

### ISSUE THREAD

**Issue by ekohlwey** [bazel-contrib/rules_oci#464]
I have a hermetic integration test I'm working on using rules_oci, docker-java and testcontainers.

I build a tar for my service in bazel:

```
oci_image(
    name = "some_server_image",
    base = "@distroless_java",
    entrypoint = [
        "java",
        "-jar",
        "/some_deploy.jar",
    ],
    tars = [":server_jar_layer"],
)

oci_tarball(
    name = "some_server_image_tarball",
    image = ":some_server_image",
    repo_tags = ["some_server:latest"],
)
```

In Java I load the image using docker-java and return the SHA based on the output of the oci_image macro:

```
    public static String loadContainerImage(String bazelTargetName) {
        String tarballTargetName = String.format("_main/%s_tarball/tarball.tar", bazelTargetName);
        DockerClient dockerClient = DockerClientFactory.lazyClient();
        try (InputStream tarball = loadRunfile(tarballTargetName)) {
            dockerClient.loadImageCmd(tarball).exec();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return getImageShaString(bazelTargetName);
    }

    public static String getImageShaString(String name) {
        String containerTargetName = String.format("_main/%s.json.sha256", name);
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(loadRunfile(containerTargetName)))) {
            return reader.lines().collect(Collectors.joining("\n"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

My test fails because there's no image with that SHA:

```
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=some_server@sha256:8c65fded57f9127056266e6caefd9fbc24cccc0f1be7b5c73fded2cc5d2233e6, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@253c1256)
```

Using `dive`, I found the SHA of the image that is installed by docker-java. It is different:

```
Digest: sha256:4d61e732c79154bdde5589ff58f1ff913cc429201956c741515e86608dc7cd00
```

Are there reasons this might be the case? One theory I have is that the image metadata changes between the oci_image build rule and docker load, either as a result of processing to a tarball or as part of the conversion from an OCI tarball to docker. Any ideas as to why this might be the case would be appreciated, as well as feedback on how to get the correct SHA from rules_oci.

**Comment by thesayyn** [comment]
This is expected as docker tarballs differ from what's in the registry, and some information is lost during conversion from oci-layout to docker tarballs.

**Comment by ekohlwey** [comment]
Thanks. Is it possible to obtain a hash from the build for the docker image?

**Comment by thesayyn** [comment]
I don't know how the docker engine calculates the image id.
