### ISSUE TITLE
`image.sh.tpl` is too unhermetically hermetic!

### ISSUE THREAD

**Issue by GregBowyer** [bazel-contrib/rules_oci#473]
I suspect this is rendered moot by https://github.com/bazel-contrib/rules_oci/pull/459, but.

We run an aggressive hermetic setup on top of NixOS, I suspect this might happen for others who are being highly hermetic.

Presently, `image.bzl` is as follows:

```python
    ctx.actions.run(
        inputs = depset(transitive = inputs_depsets),
        arguments = [args],
        outputs = [output],
        env = action_env,
        executable = util.maybe_wrap_launcher_for_windows(ctx, launcher),
        tools = [crane.crane_info.binary, registry.registry_info.launcher, registry.registry_info.registry, jq.jqinfo.bin],
        mnemonic = "OCIImage",
        progress_message = "OCI Image %{label}",
    )
```

This fails as Bazel wipes out `$PATH` and as a result, `mktemp` (and well everything) is basically none functional.

It appears that adding in the dreaded `use_default_shell_env = True` fixes this.

**Comment by rickvanprim** [comment]
That should be fixed by #459.  Apologies for the slow progress.

**Comment by thesayyn** [comment]
will be fixed by https://github.com/bazel-contrib/rules_oci/pull/569

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/569
