### ISSUE TITLE
oci_image should support stamping and creation time.

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#49]
currently, the creation time of the images is set to a fixed date for reproducibility.  this should be overridable with stamping.

**Comment by alexeagle** [comment]
@thesayyn can you point me to where we set the creation time to a fixed date? is that just a consequence of using pkg_tar?

**Comment by alexeagle** [comment]
Note, stamping as a label in `org.opencontainers.image.created` is supported as of #155

**Comment by maratsal** [comment]
Any ways to workaround this?

Without proper "created" field of config set it is not possible to get right image creation time stamp with `docker inspect` like commands.

**Comment by maratsal** [comment]
I am new to bazel and it took me couple of hours to simply understand how to build an image 😄 

as for your question, I likely can create PR for that specific case - as far as I understood you are generating and mutating image manifests and configs within this script https://github.com/bazel-contrib/rules_oci/blob/a5efb0efd19eb25e3f780b17e1bcb4d8444d6757/oci/private/image.sh.tpl by using `crane edit config` and `crane edit manifest` commands. I have checked my version of crane and I don't have that edit options, do you use some specific one there? and can you confirm that we need to add/update this "created" field of config withing that file I specified above?>

**Comment by thesayyn** [comment]
oci_image supports stamping already, as for created date stamping there's a separate issue for it. closing this as completed.
