### ISSUE TITLE
FR: Symlink blobs from `base` image instead of copying over.

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#505]
Currently when an `oci_image` depends on another one, all the blobs from the base oci_image is copied over. This was done for two reasons; 

- Avoid cascading builds. 
- Bazel did not allow symlinks inside treeartifacts that pointed outside of the treeartifact.

With https://github.com/bazelbuild/bazel/pull/21263 fixed, now we can have symlinks inside treeartifacts pointing outside.

We expect this to significantly improve build time of oci_image.

**Comment by thesayyn** [comment]
This will close: #365

**Comment by sgammelmark** [comment]
It would be great, if the provided tar-files could be symlinked as well.

I have an aspect the creates individual layers for each external python dependency. Incrementally updating the individual layers on a code change is very fast (less than a second), but updating the image can be time consuming for large images (more than 60 s). In my case, the individual blobs are exactly the same file as the tar-file, so a symlink would be far more efficient than copying the layers. 

A missing part of this is maybe that the digest of each layer needs to be computed as well? Having a rule or another mechanism for pre-computing that layer digest so layers can be re-used in different images would be great. 

Not sure if it fits this issue exactly, but the symlinking part seems to be relevant.

**Comment by thesayyn** [comment]
> It would be great, if the provided tar-files could be symlinked as well.

We have separate tracking issue for that; https://github.com/bazel-contrib/rules_oci/issues/508

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/560
