### ISSUE TITLE
Allow layers to take in files other than .tar and .tar.gz

### ISSUE THREAD

**Issue by jeremy-devuyst** [bazel-contrib/rules_oci#519]
We've been using bazel-lib tar to make layers for oci_images. It supports adding compress = "zstd".
It has actually been working fine and speeding up our builds quite a bit.
However, as I've updated bazel-lib, the generated tar file now has a .tar.zst extension instead of a .tar extension.
Only now do oci_images complain since they only accept .tar and .tar.gz files. 
I'm wondering if it should not already be allowed to take more than just those file extensions since it has been able to handle zstd compressed tars already.

**Comment by alexeagle** [comment]
Want to patch in https://github.com/bazel-contrib/rules_oci/pull/523 and check that fixes it?

**Comment by jeremy-devuyst** [comment]
Works perfectly well, thank you!
