### ISSUE TITLE
FR: Pushing images at build time

### ISSUE THREAD

**Issue by jchorl** [bazel-contrib/rules_oci#520]
We have a repo with a lot of big images. We have a remote cache. Our CI jobs effectively just call:
```
bazel run //my/image1:push
bazel run //my/image2:push
```

I've looked into bazel's recent caching improvements, however I think there's a barrier to caching's efficacy with pushes. It seems that in order to push, the image first must be pulled locally as runfiles to the push rule. However, most builds only change single images (and don't change many other images). Therefore this issue is not really about incremental pushes, but rather whether to push an image at all. On a cold worker, this means pulling all of the images from bazel's remote cache only to execute a bunch of no-op pushes (because the registry already has them).

Foremost, any guidance to improve this setup, so images don't need to pulled on every build in order to be pushed?

Based on bazel's build caching, I was exploring the idea of pushing as a _build rule_ and writing the digest to a `<target>.push` file. While outside the general paradigm of bazel builds, I believe it could bring tremendous perf/caching improvements.

It also brings ergonomics improvements, as you can run something like `bazel build --build_tag_filters=image //...` instead of needing to sequentially execute pushes or build a wrapper run-rule.

Any thoughts on this approach? Would you at all entertain the idea of such a rule in `rules_oci`?

I actually attempted to wrap `oci_push` in a build rule. Something like:
```
def _build_push_image_impl(ctx):
    out_file = ctx.actions.declare_file("_{}.push".format(ctx.attr.name))

    ctx.actions.run(
        outputs = [out_file],
        progress_message = "Running {}".format(ctx.executable.image_push),
        executable = ctx.executable.image_push,
        tools = [ctx.executable.image_push],
    )

    return [DefaultInfo(files = depset([out_file]))]

build_push_image = rule(
    implementation = _build_push_image_impl,
    attrs = {
        "image_push": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "Output of a rules_oci :push target",
            executable = True,
            cfg = "exec",
        ),
    },
    doc = """
Converts a rules_oci push run file into a build rule
""",
)
```

However this fails to execute because it cannot find `yq`. I assume because of the way the runfiles have been templated into the push script, they're not accessible in this build rule. At least not at the same location (in my push script, I see that as `readonly YQ="../yq_linux_amd64/yq"`.

Anyway, before I run much further, I figured I'd float the idea, see if it's been tried, and see if you all have a better solution/might be amenable to merging into rules_oci.

Please forgive any knowledge/understanding gaps.

Thanks!!

**Comment by alexeagle** [comment]
At a high level, I'd suggest not pushing every image on every commit. We have a solution https://blog.aspect.dev/stamping-bazel-builds-with-selective-delivery where we only try to push ("deliver") artifacts that have changed.

In your proposal, bazel build would have side-effects aside from populating bazel-out. That's surprising since a cache hit should look the same as a cache miss  from the users perspective, but a miss will push to a remote registry while a cache hit will not. OTOH if you imagine "Remote Registry is like the Remote Cache" then I see where you are coming from - the layers already built could be known to the registry-cache so the push would only include tag metadata but all layer digests are already there.

**Comment by jchorl** [comment]
Your approach is very clever. I like the idea of builds always and only producing the same `bazel-out`.

I think there is a tradeoff of ideology vs practicality. Ideologically, it makes sense that the build would not have side effects. Practically speaking, you can think of your cache as that metadata store of whether an artifact has been deployed or not. You're basically using S3/whatever remote cache as the bloom filter you mention in the blog post. For real CD deploys, you may not want to accidentally "re-deploy" but for images with unique digests/tags, there shouldn't be any harm in redeploying.

Another way to think of builds is that they _do_ have side-effects beyond populating `bazel-out`, they can populate a remote cache! Albeit, this is a pretty expected side-effect. But you can see how populating a remote registry could be viewed similarly - an expected side-effect as part of the build.

I recognize that you have a service that automates the whole redis/whatever metadata store on what's been deployed. In order to avoid building the harness of querying for artifacts + bazel run to deploy the modified images to a registry, I'll likely power on in hacking up a build step that does the push, at least to assess feasibility. I'm also keen on the ergonomics improvements of one-step build-with-filters-and-push. It avoids bazel multi-run hacks or looping over targets to push one at a time.

If this seems like something that could be more broadly useful, I could try to cut a PR with such a build rule. I can understand how it's a bit of a dangerous rule that may come with unintended side-effects, but there are GH issues floating around that make me think it'd be appreciated.

**Comment by alexeagle** [comment]
We don't have a maintenance budget here to take on more complexity, so I don't think we'd want to add a rule like that to the rules_oci public API. You could send a PR to add under examples/ if you like, with some README explaining your approach and the trade-offs.

To me the correct answer here is to explore some design for how the Bazel Remote API which knows how to communicate with a remote cache might also be able to communicate with a remote registry for container layers. For example, there's a frontend in https://github.com/buildbarn which delegates CAS/AC lookups to remote cache storage nodes, it could totally pull/push some entries from a container registry.

**Comment by Jonpez2** [comment]
FWIW we do push at build time, and we find this to work well.  We require that all of our runtimes directly reference the SHA of the image rather than tags, and then we separately use tags (encodin dates) and signatures to ensure that currently-live images are a) retained in the container repository and b) subject to a build horizon.  The tags are in our source code, so a bot updates the dates, which causes a full retag due to the magic of the bazels.  The signing happens in bulk at the very end of our push cycle, and is relatively cheap as all it needs are the full URLs of the images.
It's not trivial to get right, but the payoff is worth it.

**Comment by jchorl** [comment]
For what it's worth, I did end up implementing a build rule. Specifically I split the push into pushing the digest, and then tagging, both as cacheable build rules. This allows the digest push stage to be cached between multiple runs that tag different values. There are some valid points brought up in-thread about the registry getting out of sync with bazel cache, that must be taken into account when designing. Auth was also really annoying as env vars and other common auth mechanisms aren't automatically plumbed through to build rules. It's been great so far though.

Anyway, I'm not sure how much of this can be captured in broadly useful and safe primitives that are hard to misuse. For example, I'm not sure if today the constructs available can be arranged to separate out the digest push from the tagging operation and have the tag rely on the digest push (as the digest push is the really expensive part). Even still, that'd only be really valuable if the digest push could be efficiently cached. Alex's proposal based on a sidecar service keeping track of push operations is quite neat and attractive for other purposes.

Thanks for the insights - they certainly helped. I'll close as I don't see any obvious general-purpose improvements to be made.
