### ISSUE TITLE
FR: Return module_ctx.extension_metadata for bazel mod tidy

### ISSUE THREAD

**Issue by nobu-k** [bazel-contrib/rules_oci#529]
`bazel mod tidy` can automatically update `use_repo(oci)` if the extension returns pulled image repository names using `root_module_direct_deps` of `module_ctx.extension_metadata`.

The same approach as Gazelle should work with older versions of Bazel.

https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/bzlmod/go_deps.bzl

**Comment by alexeagle** [comment]
Ooh that sounds like a great feature, I guess it's similar to how renovate updates MODULE.bazel?

**Comment by thesayyn** [comment]
This is currently broken due to root module having use_repo calls such as `oci_crane_toolchains`

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/611
