### ISSUE TITLE
getting "/app does not exist" error when trying to run image created with oci_image

### ISSUE THREAD

**Issue by metomimic** [bazel-contrib/rules_oci#537]
hello. I'm trying to apply the rules as shown in https://github.com/aspect-build/bazel-examples/blob/main/oci_go_image/BUILD.bazel to a go repo https://github.com/a8m/ent-graphql-example and when I'm trying to run the following
```
$ bazel build //cmd/todo:service.tar
$ docker load --input $(bazel cquery --output=files //cmd/todo:service.tar)
$ docker run --rm gcr.io/example:latest
```
and I get the following:

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app": stat /app: no such file or directory: unknown.
```

I'm able to run the binary just fine with `bazel run //cmd/todo:app`. Thanks!

**Comment by finzzz** [comment]
I encountered the same behavior. I checked using `docker cp <container name>:/ test` and the binary exists.

**Comment by thesayyn** [comment]
There must be something wrong in the BUILD file which i can't tell anyhing about without seeing it. 

Also, can you use [dive](https://github.com/wagoodman/dive) to see if the directory actually exists?

**Comment by thesayyn** [comment]
Going to close as there's nothing for us to fix here. Feel free file another issue, if you think there's something needs fixing here.
