### ISSUE TITLE
Document how to migrate from rules_docker language-specific rules

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#55]
We don't want to write our own rules/macros for these in our public API, but we do need to show users what to do.
Answer might be:
- "statically compiled single file didn't need a language rule to begin with" - e.g. `go_binary`
- "paste this small macro into your repo"
- "a rule/macro is available in rules_X" (we'd do this for rules_js for example, maybe rules_python)
- "we don't support this language" (e.g. d_image, rules_d seems like it should archive)

Here is the list from https://github.com/bazelbuild/rules_docker#language-rules

-  [ ] [py_image](https://github.com/bazelbuild/rules_docker#py_image) ([signature](https://docs.bazel.build/versions/master/be/python.html#py_binary))
-  [ ] [py3_image](https://github.com/bazelbuild/rules_docker#py3_image) ([signature](https://docs.bazel.build/versions/master/be/python.html#py_binary))
-  [x] [nodejs_image](https://github.com/bazelbuild/rules_docker#nodejs_image) ([usage](https://github.com/bazelbuild/rules_nodejs#usage))
-  [ ] [java_image](https://github.com/bazelbuild/rules_docker#java_image) ([signature](https://docs.bazel.build/versions/master/be/java.html#java_binary))
-  [ ] [war_image](https://github.com/bazelbuild/rules_docker#war_image) ([signature](https://docs.bazel.build/versions/master/be/java.html#java_library))
-  [ ] [scala_image](https://github.com/bazelbuild/rules_docker#scala_image) ([signature](https://github.com/bazelbuild/rules_scala#scala_binary))
-  [ ] [groovy_image](https://github.com/bazelbuild/rules_docker#groovy_image) ([signature](https://github.com/bazelbuild/rules_groovy#groovy_binary))
-  [ ] [cc_image](https://github.com/bazelbuild/rules_docker#cc_image) ([signature](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary))
-  [x] [go_image](https://github.com/bazelbuild/rules_docker#go_image) ([signature](https://github.com/bazelbuild/rules_go#go_binary))
-  [ ] [rust_image](https://github.com/bazelbuild/rules_docker#rust_image) ([signature](https://github.com/bazelbuild/rules_rust#rust_binary))
-  [ ]  [d_image](https://github.com/bazelbuild/rules_docker#d_image) ([signature](https://github.com/bazelbuild/rules_d#d_binary))

**Comment by alexeagle** [comment]
For the 1.0 milestone I'm just going to create markdown placeholders for these and ask community contributors to help fill it in. We can try giving some hints for the ones we're familiar with.

**Comment by alexeagle** [comment]
Note, I'm thinking of dropping D from this list because it seems dead - @dcarp do you have any opinion? (I see you're the only committer recently on https://github.com/bazelbuild/rules_d/commits/master )

**Comment by kpark-hrp** [comment]
While looking for instructions on building the Python3 image layer, I stumbled here. Something like `js_image_layer` for Python3 would be awesome.
