### ISSUE TITLE
Adding bazel tag support to oci_pull (import_tags) because an oci_pull for a large image does not work when run on remote execution

### ISSUE THREAD

**Issue by steve-261370** [bazel-contrib/rules_oci#572]
I'm migrating from rules_docker's `container_pull` to `oci_pull` and the [current migration instructions](https://docs.aspect.build/guides/rules_oci_migration/#container_pull) say that the old `import_tags` attribute:

> `import_tags` is unsupported. no plans to add support for it.

We were using the `import_tags` to set the tag `no-remote` as we noticed one of the large images we pulled did not work on remote execution.  The image is over 70GB.  The build failure we get for that large image is:

> ERROR: /home/steve-261370/.cache/bazel/_bazel_steve-261370/2914a5da309afa1aa83708b7e78fb71f/external/large_image_single/BUILD.bazel:16:18: Copying files to directory large_image_single/blobs/sha256 failed: (Exit 34): Error while uploading artifact with digest '0ddf758e26952be880786328ac7091616623a2577ed9f5d74dc4a412becde8df/75284488761'

Is there a reason for there being "no plans to add support for it"?  I ended up patching in support for it (which allows the build for my large image to work remotely).  I'll send in the patch I applied shortly to add support for it.

**Comment by thesayyn** [comment]
This is a good use case, I'll think about how we could support this. the current workaround would be setting `--modify_execution_requirements=CopyToDirectory=...` https://bazel.build/reference/command-line-reference#flag--modify_execution_info

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/573
