### ISSUE TITLE
FR: Teach Renovate or provide tooling around updating oci.pull hashes in MODULE.bazel

### ISSUE THREAD

**Issue by mark-thm** [bazel-contrib/rules_oci#578]
Updating the hashes for `oci.pull` extension calls in MODULE.bazel today is a manual process, it'd be great if there were some automation to pull new hashes. Related to #391 it'd be great if such automation could update a tag (as a comment or as an argument) to make it clear what the hash refers to.

**Comment by thesayyn** [comment]
there's a discussion going on here https://github.com/bazel-contrib/rules_oci/issues/391 already. can we keep the conversation going there?

**Comment by thesayyn** [comment]
I believe this is already captured at #391 and i am going to close this issue for housekeeping purposes. 

See my comment here: https://github.com/bazel-contrib/rules_oci/issues/391#issuecomment-2125423501

**Comment by gzm0** [comment]
For reference: PR for oci.pull support in Renovate: https://github.com/renovatebot/renovate/pull/32453
