### ISSUE TITLE
ENV order not preserved in manifest file

### ISSUE THREAD

**Issue by yoks** [bazel-contrib/rules_oci#58]
Order of ENV variables are not preserved, and looks like random between builds. 

Example of the build from the same source:
`{"architecture":"amd64","created":"0001-01-01T00:00:00Z","history":[{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"}],"os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:8a3362647f3af2336d5643ebd5f185e33578636e60848c9f20bdb951cb7c2026","sha256:6b4258ba2cef84355e5d89d3a4873286edee1bee7df4ae126c72e35ef8d7e127","sha256:fb227ea45821540bd6c3e0bb2314c46fedf4baa3943a3eb9d899d750be3b2a6f","sha256:556ed1bd80e38109ce7017c0270e2cffcda68e6f707eb2977ba33e25f2de8f17","sha256:035a874c9ef9c89003c65b79569337e8c1edc1b44801776d57cd60f65e6b68cb","sha256:168960c54027796006fcf594a7ddba1904d51be842b10f051d64ddb880e6bedc"]},"config":{"Entrypoint":["/app/node/node","--unhandled-rejections=strict","/app/index.js","-c","/app/configs-runtime/current.json"],"Env":["NODE_PATH=/node_modules","LD_LIBRARY_PATH=/app/lib"]}}`

`{"architecture":"amd64","created":"0001-01-01T00:00:00Z","history":[{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"}],"os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:8a3362647f3af2336d5643ebd5f185e33578636e60848c9f20bdb951cb7c2026","sha256:6b4258ba2cef84355e5d89d3a4873286edee1bee7df4ae126c72e35ef8d7e127","sha256:fb227ea45821540bd6c3e0bb2314c46fedf4baa3943a3eb9d899d750be3b2a6f","sha256:556ed1bd80e38109ce7017c0270e2cffcda68e6f707eb2977ba33e25f2de8f17","sha256:035a874c9ef9c89003c65b79569337e8c1edc1b44801776d57cd60f65e6b68cb","sha256:168960c54027796006fcf594a7ddba1904d51be842b10f051d64ddb880e6bedc"]},"config":{"Entrypoint":["/app/node/node","--unhandled-rejections=strict","/app/index.js","-c","/app/configs-runtime/current.json"],"Env":["LD_LIBRARY_PATH=/app/lib","NODE_PATH=/node_modules"]}}`

All files and layers the same, but the final image digest is different, this makes build non-hermetic from the digest point of view.

Rules version 0.2.0
Bazel version 5.4.0

**Comment by yoks** [comment]
Looks like this is related to crane, created issue there https://github.com/google/go-containerregistry/issues/1542

**Comment by thesayyn** [comment]
closing as completed. https://github.com/bazel-contrib/rules_oci/blob/828b737ab6566142e485779f048bc5f782fdad4c/oci/private/versions.bzl#L5
