### ISSUE TITLE
Bug: "invalid path" with rules_oci 2.0.0-alpha0

### ISSUE THREAD

**Issue by mering** [bazel-contrib/rules_oci#588]
We get the following error when upgrading to the v2 pre-release:
```
invalid reference, invalid path for scheme "ocidir": bazel-out/k8-fastbuild/bin/external/repo~/package/test-image:intermediate
```

When building via `bazel build --config=remote @repo//package:test-image`. My spontaneous guess would be the Bazel version separator for external dependencies `~` or the target separator `:`.

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/622
