### ISSUE TITLE
How to use build container in bazel?

### ISSUE THREAD

**Issue by Akiyamka** [bazel-contrib/rules_oci#591]
I have Dockerfile that used for build and expose an sets of files
How I can do something like this using oci ?
```
dockerfile_image(
    name = "I_dont_care_if_its_not_hermetic",
    dockerfile = "//:Dockerfile",
    build_args = {
        "ver": "8.49.0"
    }
)

sh_binary(
    name = "test_binary",
    srcs = ["ls.sh"],
    data = [":I_dont_care_if_its_not_hermetic"],
)

```

**Comment by thesayyn** [comment]
Closing in favor of #35

**Comment by thesayyn** [comment]
FWIW, we decided that this is important enough that it should be its own ruleset.

Aspect Build is going to support https://github.com/aspect-build/rules_buildx for Dockerfile support.
