### ISSUE TITLE
Document how to replace per-platform repos

### ISSUE THREAD

**Issue by aran** [bazel-contrib/rules_oci#610]
For some time rules_oci generated per-platform repos, e.g.

```
oci.pull(
    name = "sealed_secrets_controller",
    digest = "sha256:5477ce0b63030b70fe27ffe76664bfee572059035bbaa30927394fadc0517cd3",
    image = "index.docker.io/bitnami/sealed-secrets-controller",
    # tag = "0.26.1",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(oci, "sealed_secrets_controller")
use_repo(oci, "sealed_secrets_controller_linux_amd64")
```
...
```
oci_push(
    name = "push_sealed_secrets_controller_image",
    image = @sealed_secrets_controller_linux_amd64,
    repository = REGISTRY + "/" + IMAGE_NAME,
    visibility = ["//visibility:public"],
)
```

I'm not sure exactly what version, but at some point `rules_oci` has started warning about this in both the 1.x and 2.x branches:

```
WARNING: .../MODULE.bazel:378:20: The module extension oci defined in @rules_oci//oci:extensions.bzl reported incorrect imports of repositories via use_repo():

Imported, but reported as indirect dependencies by the extension:
    ..., sealed_secrets_controller_linux_amd64

Fix the use_repo calls by running 'bazel mod tidy'.
```

I didn't see anything in the release notes about a change though.

I'm assuming I'm supposed to wrap my `oci_push` in a platform transition, or always use `--platforms` with it, but not 100% if I'm out of line with the latest recommended usage. `bazel mod sync` just removes those dependencies, and the `oci_push` then breaks. Since something has changed in the API, it would be great to have a release note or some other guidance on this. I took a brief glance through the project log but didn't immediately see what change would have done this.

**Comment by aran** [comment]
As an aside that would bypass this entirely, it would be nice if 

```
oci.pull(name = "<X>"...)
...
oci_push(...image = @<X>)
```
"just worked", but from what I can tell that's actually tricky.

**Comment by thesayyn** [comment]
This was broken in the alpha release. now we fixed it via #611 which should generate correct `use_repo` calls.

**Comment by aran** [comment]
Thank you so much! Works* for me in the 2.x branch. Not sure if you intended to merge to 1.x also, I don't see it there.

FYI, it has a kind of funny side effect: Now, to avoid the warning, I *must* `use_repo` every single platform from every single `oci.pull`, and `bazel mod tidy` will add all of those that were missing in one enormous line. (This is definitely better than `bazel mod tidy` removing things, which is an active build break risk.)

**Comment by thesayyn** [comment]
> Now, to avoid the warning, I _must_ `use_repo` every single platform from every single `oci.pull`

Unfortunately there's no way for us to limit that. However you can only add platforms you are interested in into the `platforms` attribute.

**Comment by thesayyn** [comment]
I am closing this as fixed.
