### ISSUE TITLE
2.0: consider rename of oci_tarball

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#629]
Now that it doesn't produce a tarball as a default output, the name is confusing.

Also since it's a noun, it seems like it should be build'able - but the recommended use is to run it for the side-effect of loading the layers into a daemon. So it should have a verb name like `oci_load` or `oci_daemon_load`.

While we do that we should probably rename the output group to `oci_tarball` so the migration path from 1.x is more clear.

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/636

**Comment by alexeagle** [comment]
Note, we could also pre-declare an output like `[name].tar` so you're not forced to go through the filegroup trick to request it. OTOH we want to discourage actually running `tar` to produce a huge output from an action, so I guess inconvenience is a feature.
