### ISSUE TITLE
Multiline cmd and entrypoint handling

### ISSUE THREAD

**Issue by alexnovak** [bazel-contrib/rules_oci#631]
Hello!

I noticed that oci_image seems to struggle when it's given a multiline cmd or entrypoint input. When an array containing a multiline input is provided, eg

```
[
  "/bin/bash",
  "-c",
  """
  echo hello
  echo goodbye
  """
]
```

`oci_image` will truncate the input on the newline while providing it to crane, either causing the mutation to fail, or the command/entrypoint to render inaccurately. 

`crane` expects that the cmd or entrypoint is delivered as a CSV, following [rfc4180](https://www.rfc-editor.org/rfc/rfc4180#section-2), and the newlines in cmd or entrypoint can be presented within a quoted entry.

It looks like the current script would interpret each newline in the cmd or entrypoint file as a separate --cmd entry for the mutate command. https://github.com/bazel-contrib/rules_oci/blob/main/oci/private/image.sh#L105
My understanding is that crane only expects a single cmd or entrypoint, is there a reason we handle it in this read loop?

I'd imagine we instead want to:
1. Cat the contents of the entrypoint and cmd file as the inputs to the corresponding `--cmd` or `--entrypoint`
2. When gathering the cmd/entrypoint lines for the file, ensure that we quote them, and escape all double quotes according the above rfc (`""`). 

Happy for any thoughts here, would love to understand if I'm offbase, or there's another way to do this.

**Comment by alexnovak** [comment]
Ah, seeing this is directly referenced as a consequence here https://github.com/bazel-contrib/rules_oci/pull/297#issuecomment-1708249851

Apologies if this is answered elsewhere, but is there a reason newline delimited was the decision over comma delimited?

I threw together a quick diff with what changes I think would be necessary here https://github.com/bazel-contrib/rules_oci/compare/main...alexnovak:rules_oci:main - but it fails the location_expansion test because of this convention.

**Comment by thesayyn** [comment]
> but is there a reason newline delimited was the decision over comma delimited?

i don't think so, any character would have the same consequences, as we no longer use crane.  i suggest we fix this in 2.x and leave 1.x the way it is.

**Comment by alexnovak** [comment]
Sounds fine by me! I'll double check how things work on the 2.0 branch and submit a PR

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/663
