### ISSUE TITLE
Adding a defer_download mode to rules_oci

### ISSUE THREAD

**Issue by sluongng** [bazel-contrib/rules_oci#634]
What I have observed is that rules_oci has done a great job of making the container image layers more compatible with remote cache CAS than rules_docker. However, working with container images as a whole is still a slow experience for folks using Bazel.

Most folks who are still using big legacy images with many layers and files still have to disable rules_oci + rules_docker mnemonic to exclude the outputs from remote caching and remote execution.

So here is an idea: let's accept the reality that container images are not remote cache friendly and stop including them in the build outputs. Add a "defer_download" mode to the rule, which will only store the JSON index/manifest of the image when "oci_pull" is run. Subsequent layer compositions would only use raw files and different JSON manifest/index without the base layer or tarballs.

Then we could provide a few "materialization" methods to trigger the full image build:
- Materialize the image when "oci_push" is executed.
- Materialize the image when users load the image locally to their docker daemon.
- Materialize the image when the container structure test is run (this implies the test sandbox has networking enabled).
- Provide a special build rule to "force image materialization" so that downstream rules could consume the full image. This build rules could be tagged with "manual" by default.

The materialization process could be a reusable script that downloads the layers and validates the checksum against the manifest/index kept in the build graph.

With this option available, folks would not have to include a bunch of mnemonics in their `.bazelrc` [--modify_execution_info=](https://bazel.build/reference/command-line-reference#flag--modify_execution_info) flag to avoid the network load they often needed for each build.

**Comment by thesayyn** [comment]
What you are describing is: https://github.com/bazel-contrib/rules_oci/issues/497

**Comment by sluongng** [comment]
ah ok. I did not read that issue carefully to realize it's the same idea.
Will comment there instead
