### ISSUE TITLE
multi arch images broken on 2.x

### ISSUE THREAD

**Issue by tobiaskohlbau** [bazel-contrib/rules_oci#638]
In the 2.x branch and respective releases the functionality to create multi arch images is broken due to jq overwriting the first manifest while creating the index manifest.

https://github.com/bazel-contrib/rules_oci/blob/0d90696187ab86b0ab73a7b03a163e661799a6e3/oci/private/image_index.sh.tpl#L27

Here the jq command should merge the existing manifest with the newly added one from the image. But instead it overrides the existing one. JQ has an explicit append to array operator _+=_ which is better suited in this context.

**Comment by thesayyn** [comment]
fixed by https://github.com/bazel-contrib/rules_oci/pull/633
