### ISSUE TITLE
`external/jq_linux_amd64/jq: Argument list too long` on v2 beta1

### ISSUE THREAD

**Issue by hanneskaeufler** [bazel-contrib/rules_oci#647]
First things first, running

```
bazel build //redacted/redacted
```

I get the following error

```
bazel-out/k8-opt/bin/redacted/image_redacted.sh: line 179: external/jq_linux_amd64/jq: Argument list too long
```

As versions I have:

```starlark
# WORKSPACE
    http_archive(
        name = "rules_oci",
        sha256 = "f70f07f9d0d6c275d7ec7d3c7f236d9b552ba3205e8f37df9c1125031cf967cc",
        strip_prefix = "rules_oci-2.0.0-beta1",
        url = "https://github.com/bazel-contrib/rules_oci/releases/download/v2.0.0-beta1/rules_oci-v2.0.0-beta1.tar.gz",
    )

    http_archive(
        name = "rules_distroless",
        sha256 = "4c5e98aa15e3684b580ea2e2bc8b95bac6e23a26b25ec8747c39e74ced2305da",
        strip_prefix = "rules_distroless-0.3.4",
        url = "https://github.com/GoogleContainerTools/rules_distroless/releases/download/v0.3.4/rules_distroless-v0.3.4.tar.gz",
    )

    http_archive(
        name = "aspect_bazel_lib",
        sha256 = "714cf8ce95a198bab0a6a3adaffea99e929d2f01bf6d4a59a2e6d6af72b4818c",
        strip_prefix = "bazel-lib-2.7.8",
        url = "https://github.com/aspect-build/bazel-lib/releases/download/v2.7.8/bazel-lib-v2.7.8.tar.gz",
    )
```

and my BUILD looks like

```starlark
tar(
    name = "app_layer",
    srcs = [":app"],
)

oci_image(
    name = "redacted",
    # base = "@ubuntu_noble", same error when using an oci_pull ubuntu base
    entrypoint = "app",
    os = "linux",
    architecture = "amd64",
    tars = ["@noble//libatomic1/amd64", ":app_layer"], # doesn't matter if I put any tars here or not, same error
)
```

I tried alpha3 to beta1, same error. It's peculiar that this runs for a "long" time before it fails:

```
INFO: Elapsed time: 97.368s, Critical Path: 96.02s
```

On bazel `6.3.2` (also tried with `7.2.1`, same error).
Might very well be user error of course, any pointers are appreciated. Thanks!

**Comment by hanneskaeufler** [comment]
Oh wow, I stumbled on this by luck:

```
oci_image(
    # ...
    entrypoint = "app",
)
```

errors like described above, while

```
oci_image(
    # ...
    entrypoint = ["app"],
)
```

seems to work.

**Comment by thesayyn** [comment]
This is a pretty bad footgun. entrypoint accepts both a file or a list.  the `app` in the first example is a relative label ":app", so oci_image tries to read the target as entrypoint file.

**Comment by hanneskaeufler** [comment]
> This is a pretty bad footgun.

Yeah had me scratching my head for a minute there 🤣 
Fine for me to close the issue then, or if you have any ideas on how one could add basic validation to not stumble here, also appreciated. Thanks!

**Comment by thesayyn** [comment]
Unfortunately that's a little hard to add, as `entrypoint` accepts both `[]` (a list) or `:label` (a label), former is easier to catch but the latter is not. so we can't really fix anything here. 

Closing this as there is no action for us to take.
