### ISSUE TITLE
v2beta1: `oci_push` to AWS ECR needs `ecr:BatchGetImage` permission

### ISSUE THREAD

**Issue by hanneskaeufler** [bazel-contrib/rules_oci#648]
Using `oci_push` like so:

```starlark
oci_push(
  name = "push",
  image = ":image",
  remote_tags = ["latest"],
  repository = "undefined",
)
```
and running on CI

```
bazel run //redacted:push  -- --repository XXX.dkr.ecr.XXX.amazonaws.com/XXX --tag mytag
```

yields 

```
User: arn:aws:iam::XXX:user/XXX-ecr-push is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:XXX:XXX:repository/XXX because no identity-based policy allows the ecr:BatchGetImage action
```

This was _not_ needed with `rules_docker`. Is that a bug or expected? Obviously I'd like my permissions to be as tight as can be.

**Comment by thesayyn** [comment]
We use crane in `oci_push` rule which might explain better why this permission is needed.  My instinct says that this permission is justified as oci_push is idempotent therefore needs to do some probing to determine if the image exists.

**Comment by thesayyn** [comment]
Going to close as there is nothing for us to fix here.
