### ISSUE TITLE
FR: Support for skipping unchanged digests

### ISSUE THREAD

**Issue by AFMiziara** [bazel-contrib/rules_oci#680]
I was wondering if `rules_oci` supports something similar to the parameter [skip_unchanged_digest](https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_push) that existed in `rules_docker`. Or is this a default behaviour when trying to push an image with unchanged digest to a registry?

**Comment by thesayyn** [comment]
oci_push already skips if the blob exists remotely. However, this is different than skip_unchanged_digest, where skip_unchanged_digest will skip the whole push if the manifest exists whereas oci_push will make sure everything exists including the blobs.  

Its not likely we'll support something like this as it's not always safe to skip the whole push.

**Comment by AFMiziara** [comment]
Got it. I will close this issue, thanks @thesayyn
