### ISSUE TITLE
Support stamping

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#69]
I should be able to push a specific tag with something like `bazel run --stamp --embed_label=1.2.3 //path/to:my_oci_push`

Will use https://github.com/aspect-build/bazel-lib/blob/main/docs/stamping.md

**Comment by psalaberria002** [comment]
In addition to tags, there should be support for stamping labels (and possibly other fields).

**Comment by alexeagle** [comment]
@thesayyn I have a new idea to approach this that doesn't require we run more actions, and maybe it also satisfies your desire to have a file passed in.

```
# instead of default_tags: ["latest"] we have a new metadata attribute:
oci_push(
    name = "push_image",
    metadata = {"default_tags": ["latest"]},
    image = ":image",
    repository = "index.docker.io/<ORG>/image",
)
```

`metadata` could later include custom labels as well.

`oci_push` becomes a macro so that `dict` value is supported, like we do for inline `tsconfig.json`:

```
def oci_push(name, metadata = None, **kwargs):
    if types.is_dict(metadata):
        metadata_label = "_{}_write_metadata".format(name)
        write_file(
            name = metadata_label,
            out = "_{}.json".format(name),
            content = [json.encode(metadata)],
        )
        metadata = metadata_label

    oci_push_rule(
        name = name,
        metadata = metadata,
        **kwargs
    )
```

so the attribute on the `oci_push` rule  is a label pointing to a JSON file.

Now the user can use the existing affordance for stamping in our `jq` rule:

```
jq(
    name = "stamped_metadata",
    srcs = [],
    filter = "|".join([
        "$ARGS.named.STAMP as $stamp",
        # With --stamp, use the --embed_label value, otherwise use 0.0.0
        """.default_tags = [($stamp.BUILD_EMBED_LABEL // "0.0.0")]""",
    ]),
)

oci_push(
    name = "push_image_index",
    metadata = ":stamped_metadata",
    image = ":image_index",
    repository = "index.docker.io/<ORG>/image",
)
```

WDYT?

**Comment by alexeagle** [comment]
I updated #70 with a partly-working implementation for this proposal

**Comment by thesayyn** [comment]
I love this. it's almost what I tried to describe to you in our call. like the idea that stamping is done in a separate action and fed as a file to the rule.

**Comment by malt3** [comment]
What do you think about stamping / label support for the `repository` attribute of `oci_push`?
The use case I have in mind is enabling developers to test out a container image in their private container registry (think `ghcr.io/<user>/foo`) via a build setting but also having a default setting for releases (like `company.tld/foo`).

**Comment by malt3** [comment]
Thanks! Getting the company involved may take some time. I'll discuss it internally.
Donating privately may be an option. What I can offer is helping out with maintenance and feature development in some capacity.
