### ISSUE TITLE
404 when downloading jagertracing/all-in-one

### ISSUE THREAD

**Issue by nmattia** [bazel-contrib/rules_oci#695]
I'm getting an error when pulling the following image:

```
oci_pull(
    name = "jaeger",
    digest = "sha256:f421219dbd77248301fc42ac6e8ba5026f4bada9448ab33ac89061e21cfe3fea",
    image = "docker.io/jaegertracing/all-in-one",
)
```

It looks like the image doesn't exist:

<details><summary>Download from https://index.docker.io/v2/jaegertracing/all-in-one/manifests/sha256:f421219dbd77248301fc42ac6e8ba5026f4bada9448ab33ac89061e21cfe3fea failed: class java.io.FileNotFoundException GET returned 404 Not Found</summary>

```
WARNING: Remote Cache: Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted f421219dbd77248301fc42ac6e8ba5026f4bada9448ab33ac89061e21cfe3fea
WARNING: Download from https://index.docker.io/v2/jaegertracing/all-in-one/manifests/sha256:f421219dbd77248301fc42ac6e8ba5026f4bada9448ab33ac89061e21cfe3fea failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'jaeger':
   Traceback (most recent call last):
	File "/home/.../external/rules_oci/oci/private/pull.bzl", line 350, column 55, in _oci_alias_impl
		manifest, _, digest = downloader.download_manifest(rctx.attr.identifier, "mf.json")
	File "/home/.../external/rules_oci/oci/private/pull.bzl", line 160, column 74, in lambda
		download_manifest = lambda identifier, output: _download_manifest(rctx, authn, identifier, output),
	File "/home/.../external/rules_oci/oci/private/pull.bzl", line 151, column 13, in _download_manifest
		fail(
Error in fail: Unable to retrieve the image manifest. This could be due to
*) Authentication problems. Check if `docker pull` command succeeds with same parameters.
*) Fetching an image with OCI image media types.
*) If there is a configured URL Rewriter, check that it does not block the request.

See for more: https://github.com/bazel-contrib/rules_oci/blob/main/docs/pull.md#authentication-using-credential-helpers
```

</details>

I'm authenticated and can pull other images without issues. The image that fails to pull [does exist](https://hub.docker.com/layers/jaegertracing/all-in-one/1.56/images/sha256-f421219dbd77248301fc42ac6e8ba5026f4bada9448ab33ac89061e21cfe3fea?context=explore). I've tried various combinations of setting or not setting `platforms`, using the multi-arch or arch specific digest, etc.

Is there something different about that image that makes `rules_oci` fail to fetch it? Different API version, ...?

Thanks!

**Comment by nmattia** [comment]
Running into the same issue with this image: https://hub.docker.com/layers/halverneus/static-file-server/latest/images/sha256-c387c31ffb55ac5b6b4654bc9924f73eb8fb5214ebb8552a7eeffc8849f0e7dd

**Comment by CyrusJavan** [comment]
+1 I am having the same issue when pulling postgres 
```
oci_pull(
    name = "postgres",
    digest = "sha256:4ec37d2a07a0067f176fdcc9d4bb633a5724d2cc4f892c7a2046d054bb6939e5",
    image = "docker.io/library/postgres",
    platforms = [
        "linux/amd64",
    ],
)
```

**Comment by CyrusJavan** [comment]
Upgrading from Bazel 6 to Bazel 7 fixed the issue for me.

**Comment by nmattia** [comment]
Indeed! Thanks!
