### ISSUE TITLE
Update release notes: treat #663 as breaking change

### ISSUE THREAD

**Issue by janwinkler1** [bazel-contrib/rules_oci#697]
**Proposal:** 
PR #663 changed the entry point separator from `,` to `\n`. This change can break builds relying on the old behavior. Therefore, I suggest adding #663 to the "BREAKING CHANGES" section of the v2.0.0 release notes to ensure users are aware of this modification.

**Comment by thesayyn** [comment]
Thank you. i missed that one. Fixed now.
