### ISSUE TITLE
Document how to pull an image from docker hub

### ISSUE THREAD

**Issue by qdii** [bazel-contrib/rules_oci#704]
I'm struggling to find how to simply pull an image from dockerhub.

I have the image `qdii/python-3.11-slim-libpq:latest`. How I can pull it and make it available under `@python`?

My latest attempts failed:

```
oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "python",
    tag = "latest",
    image = "qdii/python-3.11-slim-libpq",
    platforms = [
        "linux/amd64",
        "linux/arm/v7",
        "linux/arm64",
    ],
)
```

**Comment by thesayyn** [comment]
Your snippet here looks okay to me, what is it that not working for you?

**Comment by qdii** [comment]
Sorry, the failure was totally unrelated to this project. I'll close this as working as intended.
