### ISSUE TITLE
rules_oci 2.0.0 fails on Bazel 6.x

### ISSUE THREAD

**Issue by jmthvt** [bazel-contrib/rules_oci#708]
rules_oci 2.0.0 installed via WORKSPACE on Bazel 6.5.0

When attempting to build any oci_image target:

```
Traceback (most recent call last):
	File "/tmp/1d476d0a1aaa2b06b74d71fc9aefe5bf/external/rules_oci/oci/private/image.bzl", line 146, column 40, in _oci_image_impl
		use_symlinks = bazel_features.rules.permits_treeartifact_uplevel_symlinks
Error: 'struct' value has no field or method 'permits_treeartifact_uplevel_symlinks'
Available attributes: template_dict_map_each_can_return_list
```

Likely due to https://github.com/bazel-contrib/rules_oci/blob/a002dafcddffecf5a670adaea53bcb7a4ee4eeb5/oci/private/image.bzl#L146

Which seems to be only introduced in Bazel 7.1 https://github.com/bazel-contrib/bazel_features/blob/697d54eaf05ed83972204f8deee9817dcd6edfde/features.bzl#L49

**Comment by jmthvt** [comment]
OK, digging into the code, I understand it's trying to figure if the feature is available. Somehow it can't retrieve it from bazel_feature, which should be installed as a dependency in WORKSPACE:

```
load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")

rules_oci_dependencies()

load("@rules_oci//oci:repositories.bzl", "oci_register_toolchains")

oci_register_toolchains(name = "oci")
```

No idea why it's not working in my case.

**Comment by contagnas** [comment]
If you are using `WORKSPACE`, most likely something higher in your `WORKSPACE` file is pulling an older version of `bazel_features`. Try moving `rules_oci` to the top or adding `bazel_features` to the top.

**Comment by jmthvt** [comment]
Thanks @contagnas, that was it!
