### ISSUE TITLE
Bug: "invalid path" with Bazel 8

### ISSUE THREAD

**Issue by mering** [bazel-contrib/rules_oci#738]
In Bazel 8, the repo paths on disk change from `repo~` to `repo+`. This can already be tested in Bazel 7 with `--incompatible_use_plus_in_repo_names` (https://github.com/bazelbuild/bazel/issues/23127). Similar to #588, image creation fails with
```
invalid reference, invalid path for scheme "ocidir": bazel-out/k8-fastbuild/bin/external/repo+/package/test-image:intermediate
```

**Comment by mering** [comment]
Requires regclient/regclient#856

**Comment by mering** [comment]
@alexeagle could you PTAL? Thanks.

**Comment by thesayyn** [comment]
We need a new version of regctl before we can fix anything here, until then the flag can be flipped to use `~` instead.

**Comment by keith** [comment]
Note that the flag is a no-op, so it's not possible to flip back

**Comment by sudo-bmitch** [comment]
regclient just released. Hopefully that unblocks you. https://github.com/regclient/regclient/releases/tag/v0.8.0

**Comment by thesayyn** [comment]
Thank you friend :)
