### ISSUE TITLE
Osx go build to linux base image not failing. 

### ISSUE THREAD

**Issue by lromor** [bazel-contrib/rules_oci#739]
On a Mac M3 machine, an arm64 macos binary is generated: `Mach-O 64-bit executable arm64`, the os host platform is `osx`.
The binary is packaged in a .tar layer and added to a distroless base image with `os` linux. 
Running the image returns:
```
exec /foo: exec format error
```
I would expect the bazel build to preemptively fail due to the mismatch in os constraints (host os platform is "osx", target image is "linux").

What is the best solution to this problem?
Is adding a `target_compatible_with` to `@platforms//os:linux` the right direction? Should rules_oci take care of that? Should it be the user?

**Comment by manuelnaranjo** [comment]
I recently updated the sample for go image, it's not yet merged though, but you may want to look at it https://github.com/aspect-build/bazel-examples/pull/377/files

**Comment by lromor** [comment]
Thanks! That's exactly what I was looking for!
