### ISSUE TITLE
oci_pull: handle OCI-format images

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#74]
We should be able to pull an image that's published in OCI format, for example `crane manifest quay.io/buildah/stable`

Also it means we should handle more Media Types:
```
application/vnd.oci.image.index.v1+json
application/vnd.oci.image.manifest.v1+json
```

**Comment by seh** [comment]
Does google/go-containerregistry#1586 having merged (addressing google/go-containerregistry#1579) help advance this pursuit? Do we need a release there in order to make use of the new _crane registry serve_ subcommand?

**Comment by seh** [comment]
> We'll be cutting a new release for go-containerregistry and rules_oci this week.

That’s great news. Overcoming this gap leaves only bazelbuild/bazel@dfdf63a398ef3909364d31d00d1860bf42d6151f arriving in a Bazel release to get me back to where I once was with _rules_docker_. Oh, one more: @alexeagle’s stamping-related changes in #70.

**Comment by alexeagle** [comment]
Leaving this open, as the new handling of images with a crane toolchain doesn't work under bzlmod:

```
oci.pull(
    name = "buildah",
    tag = "latest",
    image = "quay.io/buildah/stable",
    reproducible = False,
)
```
->
```
ERROR: An error occurred during the fetch of repository 'rules_oci~0.3.8~oci~buildah':
   Traceback (most recent call last):
        File "/shared/cache/bazel/user_base/359b45a24cf55cc22380e941fe3bcf54/external/rules_oci~0.3.8/oci/pull.bzl", line 315, column 36, in _oci_pull_impl
                mf, mf_len = _download_manifest(rctx, rctx.attr.identifier, mf_file)
        File "/shared/cache/bazel/user_base/359b45a24cf55cc22380e941fe3bcf54/external/rules_oci~0.3.8/oci/pull.bzl", line 247, column 30, in _download_manifest
                result = rctx.execute([crane, "manifest", "{}{}{}".format(rctx.attr.image, tag_or_digest, identifier), "--platform=all"])
Error in execute: Unable to load package for @[unknown repo 'oci_crane_linux_amd64' requested from @rules_oci~0.3.8]//:crane: The repository '@[unknown repo 'oci_crane_linux_amd64' requested from @rules_oci~0.3.8]' could not be resolved: No repository visible as '@oci_crane_linux_amd64' from repository '@rules_oci~0.3.8'
```
