### ISSUE TITLE
rules_oci depends on newer rules_pkg than protobuf, causing issues

### ISSUE THREAD

**Issue by acr92** [bazel-contrib/rules_oci#99]
Hello,

I've wanted to set up rules_oci for my companys repo, and I see that it's just launched on BCR now, which is great!

So I tried to add it, and it seems to cause a conflict with the `protobuf` package:
```
Error computing the main repository mapping: protobuf@21.7 depends on rules_pkg@0.7.0 with compatibility level 1, but rules_oci@0.3.5 depends on rules_pkg@0.8.1 with compatibility level 0 which is different
```

Wasn't this one of the things bzlmod was gonna solve for Bazel? Incompatibilities between dependencies for different rule projects.

I use bzlmod for almost all of my rules, I don't have `rules_kotlin` in bzlmod yet, nor `rules_jvm_contrib` , those are the two that are missing.

My MODULE.bazel contains:
```
bazel_dep(name = "rules_java", version = "5.4.1")
bazel_dep(name = "rules_jvm_external", version = "5.1")
bazel_dep(name = "rules_python", version = "0.19.0")
bazel_dep(name = "rules_go", version = "0.38.1", repo_name="io_bazel_rules_go")
bazel_dep(name = "gazelle", version = "0.29.0", repo_name="bazel_gazelle")
bazel_dep(name = "aspect_bazel_lib", version = "1.28.0")
bazel_dep(name = "rules_oci", version = "0.3.5")
```

I've for now just added `rules_oci` as a local_path_override and changed the rules_pkg version down to 0.7.0 and that has enabled me to continue. Don't know yet what possible issues I'll encounter though.

**Comment by alexeagle** [comment]
Yeah rules_pkg broke things by setting the wrong compatibility_level. It was reported on Slack this morning
https://bazelbuild.slack.com/archives/C014RARENH0/p1679686451590549
I guess someone has to push a 0.8.2 - it's a rules_pkg bug, nothing rules_oci can do about it, sorry!
